### ISSUE TITLE
[BUG]Деклар на СБ и становление главой банды оставляет в лобби

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#1068]
Если перед стартом раунда задекларится на роль, которая не может быть антагом, например офицера СБ, то при выдаче Главы Банды игрок останется в лобби с ролью.

![image](https://user-images.githubusercontent.com/88589686/174861543-2e807b04-dd1f-469b-aee4-dc5f89ea1579.png)

ТУТ ВЫЯСНИЛОСЬ: Это работает не только с бандами. Сейчас мужик задекларился на роль рейнжера и стал клиентом-антагом. Потом как ни в чем не бывало зашел за свою майшилдированную роль, которая не может стать антагом. Антажка есть.

## ID Раунда:

14317 и 14318
## Как повторить?

Задекларится на СБ, стать главой банды.

**Comment by GrishaGold** [comment]
Очень странная хуйня
