### ISSUE TITLE
[BUG] А хуй тебе!

### ISSUE THREAD

**Issue by GrishaGold** [frosty-dev/white#1070]
Если умереть на любом мобе с лаваленда и попробовать зайти на йохея то у тебя спишут донат-поинты скажут "А хуй тебе!" и не сделают тебя йохеем. 

## Как повторить?
Зайти на свободного голема (или любую другую роль с лаваленда), умереть и попробовать зайти на йохея.

**Comment by Blessedshruman** [comment]
Фича

**Comment by AxapooH** [comment]
Чет было в гитхабе такое на недельке, да

**Comment by GrishaGold** [comment]
Так ну вроде йохеи стали отдельной ролью и это работает как надо.

**Comment by REBOLUTION228-a11** [comment]
> @TapKo4eB ты там что-то трогал

потрогай меня за хуй и яйца и
