### ISSUE TITLE
[BUG]Самый ценный ресурс станции

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#1076]
Лестницы невозможно скрафтить. Не горизонтальные, не вертикальные. Буквально, лестницы - один из важнейший частей станции, которые скрепляют нижний и верхний этаж станции. И.. их невозможно сделать.
## ID Раунда:

Все время с создания лестниц
## Как повторить?

Попытаться скрафтить лестницу

**Comment by Nikitauou** [comment]
Уже крафтятся, все виды
