### ISSUE TITLE
[IDEA] Кастрировать Йохеев

### ISSUE THREAD

**Issue by SanecMan** [frosty-dev/white#1118]
**Чё**
Да-да, вы не ослышались - фичи валеры заставляют экипаж с самого раунда прятаться от этого чёрного властелина который со смешным именем взрывает станцию и превращает экипаж в коклетки или антагов (в том числе и мага), а так как когда на станции меньше 10 игроков то это превращается вместо аутирования в работку в бей или беги
**Идеи?**
Обрезать йохеям летать на шаттле (вернуть старый), обрезать доступ к синдиприколам (потому что несмешно когда йохей вырезает станцию на которой 5 игроков аутируют в работку или взрывает нахуй всё) и сделать заход за йохеев через 30 минут с кд после смерти 10 минут
**И чё это даст**
Йохеям можно будет дать отпор как можно сделать это с генкой магом синдикатом etc. а дальше я заебался писать короче режьте йохеям всё что делает их грифозными
![image](https://user-images.githubusercontent.com/36476150/177052737-6f457a7f-6928-4af7-bcd2-825487e39022.png)

**Comment by AxapooH** [comment]
Ну, поехали.
Экипаж забивает йохея каждый раз без особых проблем. Нарезка станции идёт только при лоу онлайне. Самое страшное что вы встречаете у йохеев - пистолеты. 
Второй пункт - синдиприколов давно нет, а ты всё скулишь про них. К тому же в чём проблема спавна? Ну появится он позже, ты же продолжишь свою вонь про "Йохей всех ногебает".
Третий пук от тебя - типо щас ты слабый и нихуя не можешь? У тебя детектор йохеев, педали которые постоянно творят хуету йохеям потому что они "не экипаж", ресурсов хуева гора и дохулион возможностей. Ты блять щас можешь спокойно принести лимитку на шатл йохеев и сломать им всё к хуям, тебе ни одна педаль ничего не скажет. Рига у них нет, они не выживут после спавна.. Хули ты скулишь как сучка?

**Comment by SanecMan** [comment]
@AxapooH нахуй ты насрал шизойд
йохеи могут вырезать всю станцию если захотят
если будет такой чмоха как ты то 50/50 или шатлу пизда или ещё чё нить но точно смешное
искалка =/= убивалка
короче йохей хуй

**Comment by AxapooH** [comment]
> @AxapooH нахуй ты насрал шизойд йохеи могут вырезать всю станцию если захотят если будет такой чмоха как ты то 50/50 или шатлу пизда или ещё чё нить но точно смешное искалка =/= убивалка короче йохей хуй

Лонер может вырезать весь экипаж, нюкеры могут вырезать весь экипаж, генки могут вырезать весь экипаж, даже трейтор в соло может вырезать весь экипаж. И?
Хорошо, что у такого чмохи, как ты, нет деней на йохеев.
А, типо до этого у антагов таких целей не было? Йохеи первые в своем роде. Единственные.
Я вижу твой пуксренькь, но я не вижу дельных предложений.

**Comment by SanecMan** [comment]
> > @AxapooH нахуй ты насрал шизойд йохеи могут вырезать всю станцию если захотят если будет такой чмоха как ты то 50/50 или шатлу пизда или ещё чё нить но точно смешное искалка =/= убивалка короче йохей хуй
> 
> Лонер может вырезать весь экипаж, нюкеры могут вырезать весь экипаж, генки могут вырезать весь экипаж, даже трейтор в соло может вырезать весь экипаж. И? Хорошо, что у такого чмохи, как ты, нет деней на йохеев. А, типо до этого у антагов таких целей не было? Йохеи первые в своем роде. Единственные. Я вижу твой пуксренькь, но я не вижу дельных предложений.

При чём тут лонер который спавнится с целью взорвать станцию через час-полтора и от которого при лоупопе защититься легко - достаточно взять диск с собой
Нюкеров я уже давно не вижу
Генок и триторов можно остановить а йохей бегает с ёбаным станбатоном контрактника или с дефибом боевым (хотя они могут купить приколы что по сути им дадут безграничную власть мощь но это другое)
~~[нет деней](https://www.playground.ru/misc/news/stoit_li_donatit_v_igrah-363859#:~:text=%D0%A2%D1%8B%20%D0%BD%D0%B5%D0%B4%D0%BE%D0%BE%D1%86%D0%B5%D0%BD%D0%B8%D0%B2%D0%B0%D0%B5%D1%88%D1%8C%20%D0%BC%D0%BE%D1%8E%20%D0%BC%D0%BE%D1%89%D1%8C)~~
йохеи это опухоль

**Comment by AxapooH** [comment]
> > > @AxapooH нахуй ты насрал шизойд йохеи могут вырезать всю станцию если захотят если будет такой чмоха как ты то 50/50 или шатлу пизда или ещё чё нить но точно смешное искалка =/= убивалка короче йохей хуй
> > 
> > 
> > Лонер может вырезать весь экипаж, нюкеры могут вырезать весь экипаж, генки могут вырезать весь экипаж, даже трейтор в соло может вырезать весь экипаж. И? Хорошо, что у такого чмохи, как ты, нет деней на йохеев. А, типо до этого у антагов таких целей не было? Йохеи первые в своем роде. Единственные. Я вижу твой пуксренькь, но я не вижу дельных предложений.
> 
> При чём тут лонер который спавнится с целью взорвать станцию через час-полтора и от которого при лоупопе защититься легко - достаточно взять диск с собой Нюкеров я уже давно не вижу Генок и триторов можно остановить а йохей бегает с ёбаным станбатоном контрактника или с дефибом боевым (хотя они могут купить приколы что по сути им дадут безграничную власть мощь но это другое) ~[нет деней](https://www.playground.ru/misc/news/stoit_li_donatit_v_igrah-363859#:~:text=%D0%A2%D1%8B%20%D0%BD%D0%B5%D0%B4%D0%BE%D0%BE%D1%86%D0%B5%D0%BD%D0%B8%D0%B2%D0%B0%D0%B5%D1%88%D1%8C%20%D0%BC%D0%BE%D1%8E%20%D0%BC%D0%BE%D1%89%D1%8C)~ йохеи это опухоль

Еще раз - какие приколы? У них нет приколов синдиката, Нет алинка, НЕТ СИНДИКАТСКОГО ШМОТА!
Признай что ты просто нытик и у тебя горит.

**Comment by SanecMan** [comment]
> > > > @AxapooH нахуй ты насрал шизойд йохеи могут вырезать всю станцию если захотят если будет такой чмоха как ты то 50/50 или шатлу пизда или ещё чё нить но точно смешное искалка =/= убивалка короче йохей хуй
> > > 
> > > 
> > > Лонер может вырезать весь экипаж, нюкеры могут вырезать весь экипаж, генки могут вырезать весь экипаж, даже трейтор в соло может вырезать весь экипаж. И? Хорошо, что у такого чмохи, как ты, нет деней на йохеев. А, типо до этого у антагов таких целей не было? Йохеи первые в своем роде. Единственные. Я вижу твой пуксренькь, но я не вижу дельных предложений.
> > 
> > 
> > При чём тут лонер который спавнится с целью взорвать станцию через час-полтора и от которого при лоупопе защититься легко - достаточно взять диск с собой Нюкеров я уже давно не вижу Генок и триторов можно остановить а йохей бегает с ёбаным станбатоном контрактника или с дефибом боевым (хотя они могут купить приколы что по сути им дадут безграничную власть мощь но это другое) ~[нет деней](https://www.playground.ru/misc/news/stoit_li_donatit_v_igrah-363859#:~:text=%D0%A2%D1%8B%20%D0%BD%D0%B5%D0%B4%D0%BE%D0%BE%D1%86%D0%B5%D0%BD%D0%B8%D0%B2%D0%B0%D0%B5%D1%88%D1%8C%20%D0%BC%D0%BE%D1%8E%20%D0%BC%D0%BE%D1%89%D1%8C)~ йохеи это опухоль
> 
> Еще раз - какие приколы? У них нет приколов синдиката, Нет алинка, НЕТ СИНДИКАТСКОГО ШМОТА! Признай что ты просто нытик и у тебя горит.

дефиб боевой можно купить в аплинке синдиката? ого я не знал сэр идите нахуй с такими речами

**Comment by AxapooH** [comment]
> > > > > @AxapooH нахуй ты насрал шизойд йохеи могут вырезать всю станцию если захотят если будет такой чмоха как ты то 50/50 или шатлу пизда или ещё чё нить но точно смешное искалка =/= убивалка короче йохей хуй
> > > > 
> > > > 
> > > > Лонер может вырезать весь экипаж, нюкеры могут вырезать весь экипаж, генки могут вырезать весь экипаж, даже трейтор в соло может вырезать весь экипаж. И? Хорошо, что у такого чмохи, как ты, нет деней на йохеев. А, типо до этого у антагов таких целей не было? Йохеи первые в своем роде. Единственные. Я вижу твой пуксренькь, но я не вижу дельных предложений.
> > > 
> > > 
> > > При чём тут лонер который спавнится с целью взорвать станцию через час-полтора и от которого при лоупопе защититься легко - достаточно взять диск с собой Нюкеров я уже давно не вижу Генок и триторов можно остановить а йохей бегает с ёбаным станбатоном контрактника или с дефибом боевым (хотя они могут купить приколы что по сути им дадут безграничную власть мощь но это другое) ~[нет деней](https://www.playground.ru/misc/news/stoit_li_donatit_v_igrah-363859#:~:text=%D0%A2%D1%8B%20%D0%BD%D0%B5%D0%B4%D0%BE%D0%BE%D1%86%D0%B5%D0%BD%D0%B8%D0%B2%D0%B0%D0%B5%D1%88%D1%8C%20%D0%BC%D0%BE%D1%8E%20%D0%BC%D0%BE%D1%89%D1%8C)~ йохеи это опухоль
> > 
> > 
> > Еще раз - какие приколы? У них нет приколов синдиката, Нет алинка, НЕТ СИНДИКАТСКОГО ШМОТА! Признай что ты просто нытик и у тебя горит.
> 
> дефиб боевой можно купить в аплинке синдиката? ого я не знал сэр идите нахуй с такими речами

В аплинке нюкера или лонера. Еще раз, алинка у йохеев нет, его давно выпилили, ты ноешь с нелетала которому можешь спокойно противостоять. Ты по факту предьяви. У йохеев что, например, есть будьдог? М41? Мл90? Револьвер синдиката? От чего ты так плаяешь, мальчик? Я тебе могу весь летал йохеев перечислить с ценами, там имбы нет.

**Comment by Boroda2228** [comment]
ты забанен, так что можешь выключать свою кукарекалку
