### ISSUE TITLE
[BUG]Дизайн наезжает на текст

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#1122]
В программной центре нанитов выделение выбранной категории наезжает на текст

![image](https://user-images.githubusercontent.com/88589686/177175764-62ef504d-1adc-4b29-9997-41a47d24435f.png)

## ID Раунда:

14518
## Как повторить?

Зайти в штуку

**Comment by FelineMistress** [comment]
видимо недостаточно расширил тут еще бы 5 пикселей

**Comment by GrishaGold** [comment]
Фелин фиксил (Или не он но смысл тот же)
