### ISSUE TITLE
[BUG]Некоторые автоматы невозможно разобрать

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#1221]
Продуктовый вендомат (ОАО Четверочка-вендиг) и Частный торговый автомат не разбираются. Особенно это мешает во время восстания автоматов.
## ID Раунда:

14970
## Как повторить?

Попытаться разобрать

**Comment by FelineMistress** [comment]
сейчас заодно попробую потрогать если сработает то хорошо
