### ISSUE TITLE
[BUG] Интерфейс Отладки бота проёбан

### ISSUE THREAD

**Issue by jhnazar** [frosty-dev/white#1270]
## Как повторить?
Нажимаем по собранному эндоскелету борга и встречаем проёбанный интерфейс
![image](https://user-images.githubusercontent.com/62169344/183618020-b3235f0c-3a2c-4226-bccd-d48675df6e93.png)

**Comment by Valtosin** [comment]
https://github.com/frosty-dev/white/commit/33264583be156b40b4897ec94c7bfd9f63540eb6
