### ISSUE TITLE
[BUG] Фугасный ракета синди маулера

### ISSUE THREAD

**Issue by jhnazar** [frosty-dev/white#1306]
## Как повторить?

- Фугасная ракета не взрывается при контакте с врагом что привело к этому приколу:

![image](https://user-images.githubusercontent.com/62169344/184891659-36df4d4d-0b07-4aa9-8c22-a517f0bb1d53.png)

- Также ракета при прямом контакте с человеком не взрывается (Капитан героически принял снаряд на себя и буквально впитал её себя и получил примерно 20% урона).

- Ракета не взрывается при контакте со стенкой

**Comment by GrishaGold** [comment]
Ракеты против мехов а не людей... Даже обычная ракетница так работает. Хз я думаю фиксить не будут.
