### ISSUE TITLE
[BUG]Фактор настроение от еретика ломает остальные

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#1359]
Фактор про руки после похищения еретиком сломан. Где-то что-то проебано

![image](https://user-images.githubusercontent.com/88589686/186970628-c98b377c-ec08-4cfa-8dbb-b1b87424c882.png)

## ID Раунда:

15340
## Как повторить?

Получить и наслаждаться

**Comment by GrishaGold** [comment]
Валера чинил.
