### ISSUE TITLE
[BUG]Монохромия не пропадает

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#1401]
Получил ослеплением, появился эффект монохромии. Ослепление прошло, а эффект остался навсегда
Также раньше иногда монохромия не спадала после сна в крио, если его прервать(?) руками как-то, например потрясти тело для пробуждения
## ID Раунда:

15486
## Как повторить?

Ослепить человека, подождать до окончания ослепления.

**Comment by Fesiks** [comment]
пропадает, вроде...
