### ISSUE TITLE
[IDEA] remove птср

### ISSUE THREAD

**Issue by RedFoxIV** [frosty-dev/white#141]
на него никто не смотрит дальше фобии, он ничего не приносит в игру, кроме какой-то хуйни уровня даркрп для психолога - профессии, которая не имеет смысл вне контекста HRP параши.

**Comment by RedFoxIV** [comment]
пиздец блять, эта хуйня ещё и 100 метакэша стоит нахуй
нахуй нахуй

**Comment by TequilaSunrise272** [comment]
если убрать стоимость этой хуйни за 100 метакэша и сделать другой способ убирать ПТСР, то можно будет хавать причмокивая

**Comment by daxsc** [comment]
> и сделать другой способ убирать ПТСР
например

**Comment by SanecMan** [comment]
> на него никто не смотрит дальше фобии, он ничего не приносит в игру, кроме какой-то хуйни уровня даркрп для психолога - профессии, которая не имеет смысл вне контекста HRP параши.

Хуета не даёт нормально играть, а убрать её так это нужно ждать психолога который за 100 меты снимет её и больше не захочет снимать.

**Comment by TequilaSunrise272** [comment]
> например
кормить галлюциногеном каким или заставить ждать 5 минут перед тем, как ПТСР можешь вылечить после начала терапии

**Comment by RedFoxIV** [comment]
kebab removed

**Comment by RedFoxIV** [comment]
забыл закрыть
