### ISSUE TITLE
[BUG] Белиберда вместо русских слов

### ISSUE THREAD

**Issue by SanecMan** [frosty-dev/white#142]
## Как повторить?
Ввести в ![image](https://user-images.githubusercontent.com/36476150/124303527-c4e24680-db8c-11eb-9be2-2da093ea4f52.png) любое русское слово, от чего вместо, например, слова "Химия" отображается ![image](https://user-images.githubusercontent.com/36476150/124303602-d88dad00-db8c-11eb-94df-4ed01de4b79c.png)

**Comment by Valtosin** [comment]
Не могу воспроизвести, нужно немного больше информации.

ID-раунда, версия Windows, версия BYOND на момент появления ошибки и системная локаль (на каком языке винда).

**Comment by SanecMan** [comment]
> Не могу воспроизвести, нужно немного больше информации.
> 
> ID-раунда, версия Windows, версия BYOND на момент появления ошибки и системная локаль (на каком языке винда).

Имя ОС	Майкрософт Windows 10 Pro
Версия	10.0.19042 Сборка 19042
Изготовитель ОС	Microsoft Corporation
Тип	Компьютер на базе x64
Язык системы	Россия
![image](https://user-images.githubusercontent.com/36476150/124478519-77a1e700-ddcf-11eb-9c38-b9d6334c7c43.png)

**Comment by Valtosin** [comment]
Вероятнее всего проблема в том, что скомпилирован и запущен сервер на последней 514.1557.

Возможное решение: Обновить клиент до последней BETA версии 514.1557.

Есть другие идеи, @SanecMan?

**Comment by SanecMan** [comment]
> Вероятнее всего проблема в том, что скомпилирован и запущен сервер на последней 514.1557.
> 
> Возможное решение: Обновить клиент до последней BETA версии 514.1557.
> 
> Есть другие идеи, @SanecMan?

Нету, можешь закрывать ишью.
