### ISSUE TITLE
[IDEA] Хохлодемон

### ISSUE THREAD

**Issue by Gustekkus** [frosty-dev/white#143]
### **Добавить Хохлодемона.**

_Прототип был создан кнопочками и был на 80% играбелен._

**Внешний вид:**
Обычный спрайт [Свиньи](https://www.youtube.com/watch?v=9whQIbNmu9s), но с рогами.

**Способности:**

- Blood Crawl обычного демона
- Изменённый Tail sweep мамки аналиенов
- Удар с руки в пол силы обычного демона
- Все звуки демона изменены на хрюки
- Во время _невидимости_ _(или полёта в Blood Crawl, хуй знаю как обозвать)_ издаются громкие хрюки, выдающие местоположение хохлодемона
- При убийстве Хохлодемона, все сьеденные жертвы выпадают Хохлами
- При убийстве Хохлодемона выпадает сало
- При поедании Хохла или Сала восстанавливается здоровье
- При поедании обычного человека здоровье восстанавливается с коэф 0.2 от обычного восстановления

**Альтернатива:**
Научить меня через VV давать животному возможность пиздить с руки

**Comment by jhnazar** [comment]
БЛЯТЬ!
