### ISSUE TITLE
[BUG]Металлопена не закрывает разгермы

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#1436]
Это я кинул гранату с пеной рядом с дыркой, а он даже ее не покрыла. Классно работает, космос снаружи зато покрыло.

![image](https://user-images.githubusercontent.com/88589686/190470979-682a65b9-cfb0-4d1e-9ae5-20937b0f16ab.png)
![image](https://user-images.githubusercontent.com/88589686/190471008-c819fcf5-9b90-49c9-a27f-c36c9b0be6ff.png)

## ID Раунда:

15647
## Как повторить?

Использовать гранату с красного тулбокса по назначению

**Comment by GrishaGold** [comment]
Фиксили?
