### ISSUE TITLE
[BUG] некликабельный космос на станции аутистов

### ISSUE THREAD

**Issue by Alexs410** [frosty-dev/white#147]
## Как повторить?
Выйти в космос на юг у аутистов. Зайти за красную линию (5 тайлов от шлюза), понять что всё, приехали и ты никак не развернешься. PIZDEC.

![image](https://user-images.githubusercontent.com/36363724/124393813-fbdb6800-dd04-11eb-8ff2-e9ff73c6c9c7.png)

**Comment by SanecMan** [comment]
Дополняю тем что там нету ваккума но дышать не сможешь, как и двигаться, строить и т. д.

**Comment by Valtosin** [comment]
Должно быть решено тут: da399e4b1a78ed6adc5b0287dd937777a3e0c6f6
