### ISSUE TITLE
[BUG]Сломалась возможность прятаться за лавр

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#1486]
Если тыкать на способность СПРЯТАТЬСЯ, то ничего не будет происходить.
## ID Раунда:

15838
## Как повторить?

Попытаться спрятаться под стол за лавру

**Comment by FelineMistress** [comment]
блять чинили же уже

**Comment by ThereDrD0** [comment]
> блять чинили же уже, опять?
Не опять, а снова

**Comment by GrishaGold** [comment]
Костыли
