### ISSUE TITLE
[IDEA] Чек-лист

### ISSUE THREAD

**Issue by Gustekkus** [frosty-dev/white#150]
### Накодить чек-лист при первом входе на сервер. 
В чек-лист входит ссылка на Вики с правилами и ссылка на Дискорд. При переходе по обоим ссылкам ставится галочка и начинается [10-15 минутный](https://youtu.be/Vo-0m54iBsA)  таймер после которого можно будет начать играть. Так же можно добавить верефикацию через бота, что человек реально зашёл на канал и зарегистрировался.

**Плюсы:**

- Приток ньюфагов на канал
- Приток ньюфагов в фанклаб
- Отсеивание рандомов "весельчаков" (хочешь играть, делай что сказали или уебывай)
- Палки в колеса набегаторам обходяторам, ибо помимо нового аккаунта бьенда надо делать и новый аккаунт Дискорда, + ожидание

**Минусы:**

- Отсеивание ньюфагов, более меньший приток онлайна

_так же можно добавить педальную кнопку, чтобы можно было отменить привязку дискорда к бьенду, если какой-то проверенный человек решил поменять сикей и т д_

**Comment by RedFoxIV** [comment]
звучит как говно

**Comment by Blessedshruman** [comment]
>приток ньюфагов на канал
Нет смысла, они все равно приходят как только более-менее укореняются или получают бан/пишут банхим, а большего нам и не надо
>приток ньюфагов в фанклаб
Нахуя?
>Отсеивание рандомов "весельчаков" (хочешь играть, делай что сказали или уебывай)
Каких весельчаков? Весельчаки это пацаны, которые заходят в дискорд насрать и не играют. Ситуация наоборот называется уже набегатель и о ней...
>Палки в колеса набегаторам обходяторам, ибо помимо нового аккаунта бьенда надо делать и новый аккаунт Дискорда, + ожидание
Единственная вещь, которая действительно будет достигнута твоей хуйней, но у нас сейчас нет какой-то острой проблемы набегаторов. Набеги происходят раз-два в месяц и банится это спокойно. Определенно не стоит уменьшения онлайна.

**Comment by daxsc** [comment]
Не слишком ли много навязчивых условий чтоб просто поиграть? У нас и так есть плюсы за привязываение аккаунтов. Может лучше для большинства этих действий давать бонусы и говорить об этом новичкам когда они впервые заходят или в мотд написать..

**Comment by RedFoxIV** [comment]
протухло

**Comment by Gesugao-san** [comment]
а я бы запилил..

**Comment by RedFoxIV** [comment]
не надо нам онлайн давить
