### ISSUE TITLE
[BUG] Шедоулинги

### ISSUE THREAD

**Issue by KOSTYARON** [frosty-dev/white#151]
Если на сервере нет 10 людей, то может выпасть шедоулинг, которому можно 10 траллов для асценда.
## ID Раунда:9327

9327

## Как повторить?
 никак блять валера что ты придумал

**Comment by Alexs410** [comment]
> никак блять валера что ты придумал
Так то их до конца допиливал @Blessedshruman

**Comment by RedFoxIV** [comment]
работать

**Comment by Waklaidan** [comment]
а шедоулингов же убрали?
Вместо на них на ТГ кошмары

**Comment by Valtosin** [comment]
Fixed
