### ISSUE TITLE
[IDEA] Vein corp guns, или же переработка бомжебрига.

### ISSUE THREAD

**Issue by Alexs410** [frosty-dev/white#152]
Переработка бомжебрига. Замена карманных еганов, которые ВНЕЗАПНО лезут в карман и являются хорошей альтернативой. 
Сначала закодить, наспрайтить, а потом уже балансить от игры.

Гематическое вооружение. 

Экспериментальная наплечная гематическая система. Питается из баков с переработанной кровью пользователя. (Точно не спизженно из Death Stranding) 
Гематическое оружие будет иметь два режима: нелетальный, летальный. 
Их урон. 
32 по стамине или же 16 брут урона без шанса на застревание.
Нечто среднее между энергетическим оружием и баллистикой. Леталом и нелеталом.
Кончились патроны? Время терять кровушку, так как система берет кровь только из тела владельца. (Это не исключает абузы переливания крови, но на это нужно время, а в бою это может быть проблематично.)
Нужен летал? Переключай пушку в другой режим. Это будет использовать в 2 раза больше заряда. Будучи слабее, чем большая часть дальнобойного оружия они могут перезаряжаться между перестрелками без магазинов и прочего. 

Подвиды: 

Гематический усмиритель. 
Только нелетальный урон, 12 зарядов. 

Гематическая винтовка. 24 заряда, два режима. 

Герметический карабин. 32 (16 выстрелов) заряда, только летал, может стрелять очередями по 2 пули. 

У каждой установки различное количество генерируемых зарядов, на заряд требуется 5 единиц крови. (Безопасно можно израсходовать до 85 единиц крови или же 17 зарядов, потом начнешь получать оксиурон.) 

>TL;DR
Фиксированный урон у оружия. 
Либо 32 стамины, либо 16 брута без эмбида. 
20 крови за 4 заряда.
Три вида пушек по аналогичности. 
Дизейблер, е-ган, карабин из карго.

Дискасс.

**Comment by RedFoxIV** [comment]
тем временем химик:
![изображение](https://user-images.githubusercontent.com/38788538/124611193-e0459e00-de79-11eb-8540-708539034215.png)

**Comment by Alexs410** [comment]
Бегаешь с капельницей и хуяришь людей. Круто.

**Comment by RedFoxIV** [comment]
химик может буквально за 6 кликов сделать 100u крови своей группы для переливания
если гуи диспенсера уже открыто, то 5 кликов

**Comment by RedFoxIV** [comment]
протухло
