### ISSUE TITLE
[IDEA] Бафф термомашин

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#153]
Бафф термомашин, которых Валера занерфил в говно.
Сейчас термомашины используются для бомб, ТЭГа, но при этом они потребляют бешенное количество энергии (20 мегаватт при т2 деталей, 50 мегаватт при блюспейс). Однако это только нагревание. А в атмосе ТЭГ почти нельзя нормально перестроить, в то время как тэг в инженерке при попытке сделать по инструкции Валеры, огонь просто похуй на стенки и нагревает всю комнату вместе с тэгом. И при этом нагреватель потребляет больше чем ты получаешь энергии.
Изменить потребление энергии.
Уменьшить потребление энергии термомашинами в 10-20 раз или сделать тэги более удобными. Не просто удобней, а в разы удобней.

**Comment by Valtosin** [comment]
e6e747f264a1df7edb4fbe9083fd9b06fb0d1fa2
