### ISSUE TITLE
[BUG] Космос рейджеров сломан. 

### ISSUE THREAD

**Issue by Alexs410** [frosty-dev/white#155]
## Как повторить?
Зайти за рейнджеров, полететь на любую точку, кроме дружественной станции. Получить пустой космос.

**Comment by Alexs410** [comment]
@Valtosin

**Comment by Valtosin** [comment]
блять какого хуя

**Comment by Valtosin** [comment]
2d9b15368cd0bb04bc9fae0f88d08d857eba444e
