### ISSUE TITLE
[IDEA] вернуть консоли управления антиметеорной защиты станции.

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#156]
Их выпилили по миссклику, надо вернуть.

**Comment by Gesugao-san** [comment]
dbcb55326328422fc15c9263b18df59d42c2d41c

**Comment by Gesugao-san** [comment]
я сделяль, босс @Valtosin

**Comment by Valtosin** [comment]
> я сделяль, босс @Valtosin

![image](https://user-images.githubusercontent.com/10297716/124941334-eb90f900-e034-11eb-823c-4d0d4690cde2.png)
