### ISSUE TITLE
[IDEA] Метакэш и роли

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#158]
На данный момент за гринтекст выдается 55 метакэша, за эвакуацию 15. Не думаю, что как-то интересно будет сидеть и зарабатывать такую валюту, если даже за банальное существование (у кошмара, например, нет заданий, но оно автоматически выполняется и дает награду, даже если ты умер) тебе дают все те же 55 метакэша.

ЧТО Я ПРЕДЛАГАЮ СДЕЛАТЬ:
1. У трейторов/генокрадов вместо стандартных 55 метакэша давать суммированное кол-во за каждое выполненное задание.
Например: задание с убийством, задание с кражей ИИ, задание с эвакуацией; 20+40+10

2. Убрать выдачу метакэша у гостролей. По сути это халявное бабло.

3. Обрезать или изменить систему выдачи метакэша у всяких кошмаров, ЕРТ, шизоидов и т.д и т.п
У кошмара и ЕРТ задание автоматически выполняется, даже при условии, что ты труп. Либо придётся делать проверку на то, живой ли игрок, либо насрать в яйца. 
У шизоидов слишком легкое задание. Проще уменьшить выдаваемый метакэш за спасение.

**Comment by Valtosin** [comment]
Я предлагаю тебе накодить

**Comment by TequilaSunrise272** [comment]
я не умею

**Comment by Valtosin** [comment]
Наш герой

**Comment by daxsc** [comment]
https://github.com/frosty-dev/white/commit/8d6596e23445ccf3ca9c7355adea8636c92314b1
https://github.com/frosty-dev/white/commit/b59ebee6e4e3c79d159d66e523b0e4b5e4b3f81c
