### ISSUE TITLE
[BUG]В поясах потерян слот

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#1588]
Фелин добавлял в пояса слот, но видимо из-за мержа с ТГ, он слетел.
![image](https://user-images.githubusercontent.com/88589686/197356268-f6786a3c-bd11-4c6d-8ceb-8b24c2f30814.png)

## ID Раунда:

16143
## Как повторить?

Не найти слот

**Comment by FelineMistress** [comment]
Да, я завтра поправлю
