### ISSUE TITLE
[IDEA] Добавить генератор в пермабриг

### ISSUE THREAD

**Issue by MrDeni4** [frosty-dev/white#159]
Очень часто инженеры не настраивают материю, а если и настраивают, на перму не хватает мощности, и зэки сидят в полной тьме. На топливо можно дать 60 кристаллов электричества (жидкое серебро + жидкое электричество). Расположить его предлагаю в комнате с уборочными принадлежностями вместе с гаечным ключом, чтобы была возможность его настроить. Идею поддержал один из кодеров (сикей Gesugao-san, если не ошибаюсь).

**Comment by Valtosin** [comment]
У нас единая энергосеть пока что в коробке. Планируется поделить энергосети на несколько и тогда будет возможность отдельно управлять энергией. Сейчас в целом никто тебе не запрещает отрезать бриг от энергосети станции или поставить буффер в виде смеса и по быстрому поставить пакман в ней. Посмотрим.

**Comment by Gesugao-san** [comment]
@Valtosin я могу это реализовать, нужно?

**Comment by Valtosin** [comment]
Два буфферных смеса для брига этому парню 522677d5099af592e46f9fa072f3c42274f40842
