### ISSUE TITLE
[BUG] Черный Ящик у рейнджеров

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#160]
При выполнении миссии на Черный Ящик пишется - заказ провален.

## Как повторить?

Начать любую миссию на Чёрный Ящик. Доставить чёрный ящик на станцию. Привести его на мостик и активировать. После исчезновения ящика пишет, что миссия провалена.
![image](https://user-images.githubusercontent.com/44509388/125159448-0f148a80-e180-11eb-9e32-e39bc54ee0b2.png)

**Comment by RedFoxIV** [comment]
@Valtosin пофиксил или как?
