### ISSUE TITLE
[IDEA] Баффнуть ТЭГ

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#161]
Сейчас ТЭГ производит крохи энергии даже на крайне хороших смесях и при высоких температурах. Уменьшить генерацию энергии в 1000 раз было слишком, как насчет увеличить существующую генерацию в 10 раз? Это всё ещё будет сложно запитать, но можно. Ибо максимум у меня было 21 киловатт, что очень мало. Я не уверен, что без трития это вообще можно запитать нормально.

**Comment by Erring** [comment]
И ещё бы антиматерию баффнуть. А то 5 киловатт это пиздец

**Comment by Alexs410** [comment]
> И ещё бы антиматерию баффнуть. А то 5 киловатт это пиздец

Кстати, у нас вроде формула сломана, ща потыкаю

**Comment by Alexs410** [comment]
@Erring 
https://github.com/frosty-dev/white/commit/d8bb9dc2ecded05176344d8a327517ec444f1724

**Comment by Erring** [comment]
Подожди, оно делит на кол-во ядер?

**Comment by Gesugao-san** [comment]
@Erring @Alexs410 верно понял?
@Valtosin норм?

**Comment by RedFoxIV** [comment]
что-то сделали
что конкретно - непонятно, но что-то точно сделали

**Comment by Gesugao-san** [comment]
@RedFoxIV
пытался сделать: https://github.com/frosty-dev/white/pull/167
пытаюсь сделать: https://github.com/frosty-dev/white/pull/192
наверное, буду просто бранч пересоздавать
а иссуй открой, ибо работаю над этим

@Erring
переименуй в "Баланс ТЭГа"

**Comment by Gesugao-san** [comment]
https://github.com/frosty-dev/white/pull/198

**Comment by Gesugao-san** [comment]
Замержено, можно закрывать
@Valtosin, @RedFoxIV, @Alexs410, @jhnazar

**Comment by RedFoxIV** [comment]
погоди, а чё гитхаб говорит, что он пр не замержен
