### ISSUE TITLE
[BUG] Нехватка ускорителей гравитона

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#162]
В автомате есть 5 гравитонов, но на самом деле только 2.

## Как повторить?
При покупке 2 гравитонов в автомате мехкомпа, остальных нельзя купить, ибо пишет: MechComp vending machine бипает, "Sold out of mechcomp graviton accelerator."
x

**Comment by RedFoxIV** [comment]
![изображение](https://user-images.githubusercontent.com/38788538/125172123-6b979a00-e1c0-11eb-9cde-0cd1d3ce6735.png)

**Comment by Erring** [comment]
![image](https://user-images.githubusercontent.com/44509388/125172251-48b9b580-e1c1-11eb-8644-f400c86f41d8.png)
![image](https://user-images.githubusercontent.com/44509388/125172291-861e4300-e1c1-11eb-9003-3c8d02693369.png)
Я просто охуел когда кончилось
