### ISSUE TITLE
сделать так что-бы шадовлинги видели где светло[IDEA]

### ISSUE THREAD

**Issue by Chilipila** [frosty-dev/white#163]

**Comment by Valtosin** [comment]
Ниче не понял, в каком плане?

**Comment by Alexs410** [comment]
У них вроде максимальное ночное зрение и они не видят разницы между светом и тьмой, но свет их обжигает шо пиздец.

**Comment by Valtosin** [comment]
У них уже есть переключатель для этого случая в глазах.

**Comment by Chilipila** [comment]
я смотрел, на минимальном и на максимально разницы нет

**Comment by Gustekkus** [comment]
Там есть разница мин макс, у тебя сломано, проблема в том, что если минимум поставить, видно где светло, но не видно в темноте, если наоборот поставить, то наоборот
