### ISSUE TITLE
[IDEA] Добавить дварфам ascii-графику

### ISSUE THREAD

**Issue by MrDeni4** [frosty-dev/white#164]
Ну а что, и оригинально, и со спрайтами проблемы не будет.

**Comment by Valtosin** [comment]
Как и желающих поиграть. Код открытый, можешь всё перерисовать при желании.

**Comment by Nervol** [comment]
Ну ты и ебанутый бляяяяяя

**Comment by RedFoxIV** [comment]
![SdsVlNmb6zo](https://user-images.githubusercontent.com/38788538/127257381-c959b95a-5677-4b67-8db9-579c9d454ae3.jpg)

**Comment by Gesugao-san** [comment]
не актуально из-за: https://github.com/frosty-dev/white/pull/188
