### ISSUE TITLE
[IDEA] Инструменты в бар

### ISSUE THREAD

**Issue by KOSTYARON** [frosty-dev/white#165]
Добавить музыкальные инструменты (гитару и другие) в пластитановую ротацию бара

**Comment by Gesugao-san** [comment]
@KOSTYARON эти?
![image](https://user-images.githubusercontent.com/28023014/125580498-392a31f8-22d0-493e-85fb-efdeb3da8308.png)

**Comment by KOSTYARON** [comment]
Да

**Comment by KOSTYARON** [comment]
Вариация пианино там есть, а вот гитар и скрипок - нет.

**Comment by Gesugao-san** [comment]
@KOSTYARON как-то так
@Valtosin норм?

**Comment by Valtosin** [comment]
Мы туда телевизор хотим впилить, но похуй пойдёт

**Comment by Gesugao-san** [comment]
А, да? Могу и его, без проблем, пристроим

**Comment by Gesugao-san** [comment]
Извиняюсь за тупой вопрос, а какой? Этот
https://github.com/frosty-dev/white/blob/master/white/valtos/code/gamemode/rospilovo.dm#L540
или
https://github.com/frosty-dev/white/blob/master/code/game/machinery/computer/camera.dm#L250
этот?

**Comment by Valtosin** [comment]
никакой
