### ISSUE TITLE
[IDEA]

### ISSUE THREAD

**Issue by 1NC06Nl70** [frosty-dev/white#168]
Впишите в описание к серверу "оставь надежду всяк сюда входящий"
Идеально подходит

**Comment by Gesugao-san** [comment]
Во-первых, нет заголовка,
Во-вторых, идеально не подходит, поэтому @Valtosin закрывай

**Comment by RedFoxIV** [comment]
вы запостили несмешное

**Comment by Gesugao-san** [comment]
> вы запостили несмешное

«милорд, вы заплатили КРИНЖ. люди покидают нас»

**Comment by jhnazar** [comment]
Шо за хуйня
