### ISSUE TITLE
ПОЧИНИТЕ ТОРУС БЛЯЯЯЯЯЯЯЯ

### ISSUE THREAD

**Issue by Alexs410** [frosty-dev/white#169]
ПОЧИНИТЕ ТОРУС БЛЯЯЯЯЯЯЯЯ

_Originally posted by @jhnazar in https://github.com/frosty-dev/white/issues/167#issuecomment-879798496_

**Comment by Valtosin** [comment]
А что сломано?

**Comment by Gesugao-san** [comment]
А где сломано?

**Comment by jhnazar** [comment]
Газы не всасываются нормально в торус

**Comment by Valtosin** [comment]
чини

**Comment by jhnazar** [comment]
ДА ТЫ ЧЁ? БЛЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯЯ

**Comment by Valtosin** [comment]
работает
