### ISSUE TITLE
[COPYRIGHT] Автомат големов

### ISSUE THREAD

**Issue by Gesugao-san** [frosty-dev/white#170]
## Сообщение текстом

> Можешь написать на гитхабе вайта про спизженный спрайт у автомата големов?
> А то зарегистрироваться там не могу

by: @Rotipik#8251 (Discord ID: 729632082464342096)

### Примечение
Попытался помочь с акком, не получилось.

**Comment by RedFoxIV** [comment]
а чё там не так

**Comment by Gesugao-san** [comment]
> а чё там не так
> 

сам хз, перешлю ему вопрос чуть позже

**Comment by Gesugao-san** [comment]
> а чё там не так

**Rotipik**: _У автомата големов на своём корабле нет спрайта, вот что там.
Я несколько раз играл и смотрел, спрайт спиздили._

**Comment by Valtosin** [comment]
> > а чё там не так
> 
> **Rotipik**: @RedFoxIV, @Valtosin, _у автомата големов на своём корабле нет спрайта, вот что там.
> Я несколько раз играл и смотрел, спрайт спиздили._

Почини?

**Comment by Gesugao-san** [comment]
> > > а чё там не так
> > 
> > 
> > **Rotipik**: @RedFoxIV, @Valtosin, _у автомата големов на своём корабле нет спрайта, вот что там.
> > Я несколько раз играл и смотрел, спрайт спиздили._
> 
> Почини?

![image](https://user-images.githubusercontent.com/28023014/125764480-f799c51f-6e09-43c8-8096-12b43224d59b.png)

**Comment by RedFoxIV** [comment]
почему тут тег [copyright], если речь идёт про отсутствующий спрайт?
чё мы должны делать, если нам сказали какую-то хуйню и ожидают от нас действий

**Comment by Gesugao-san** [comment]
> почему тут тег [copyright], если речь идёт про отсутствующий спрайт?
> чё мы должны делать, если нам сказали какую-то хуйню и ожидают от нас действий

> https://github.com/frosty-dev/white/issues/170#issuecomment-880425479: _Я несколько раз играл и смотрел, спрайт [спиздили](https://youtu.be/rlDCBG2Rd-4)._

**Comment by RedFoxIV** [comment]
>у автомата големов на своём корабле нет спрайта, вот что там.
Я несколько раз играл и смотрел, спрайт спиздили.
чтобы спиздить спрайт он сначала должен быть
