### ISSUE TITLE
[BUG] @baldenysh текстуры верни

### ISSUE THREAD

**Issue by Gesugao-san** [frosty-dev/white#171]
@baldenysh, [ТЫ ВСЁ ИСПОРИЛ!!1!](https://youtu.be/amDhDF87VF8?t=12)

### ДО
Код:
![Code_ouuBwun8cu](https://user-images.githubusercontent.com/28023014/125743053-3f28b4fa-50a1-4e63-bb27-126f5aec0a29.png)
Файл спрайтов:
![Code_8vnktNUiD8](https://user-images.githubusercontent.com/28023014/125741401-1ed7f6a4-f72b-4178-922c-8d07538b2ded.png)
В редакторе (и в игре):
![StrongDMM_DUkWu1fUaK](https://user-images.githubusercontent.com/28023014/125740938-ecf53ed9-2610-4c68-9de4-ac92f184aecc.png)

### ПОСЛЕ
Код:
![chrome_67rhZx7XVx](https://user-images.githubusercontent.com/28023014/125743153-3d9f77c2-5486-491a-9e22-7ca506f8cb5b.png)
Файл спрайтов:
![image](https://user-images.githubusercontent.com/28023014/125740601-6ffc2057-b824-49d4-9ce1-74a457f85b52.png)
В редакторе (и в игре):
![StrongDMM_7jFiLwHfBz](https://user-images.githubusercontent.com/28023014/125740517-18a77fbf-81c3-41c4-97b7-6ab9c757736f.png)
![dreamseeker_SK4d31Xhr7](https://user-images.githubusercontent.com/28023014/125743369-e6c5d34d-52f7-4afe-a041-eb349c8e8fe2.png)

### ЧЕМ НАСРАЛ
 → https://github.com/frosty-dev/white/commit/067ba39571d8289da2f91f64d7ce2716fb6a5f04

**Comment by RedFoxIV** [comment]
помогите балдёныш грифонит репу на гитхабе

**Comment by RedFoxIV** [comment]
уже всё
