### ISSUE TITLE
[IDEA] Огнетушитель не пшш пшш

### ISSUE THREAD

**Issue by AxapooH** [frosty-dev/white#1724]
Не пш пш, Валера учись в баланс.

**Comment by GrishaGold** [comment]
Отклонено

**Comment by Boroda2228** [comment]
О нет, суровый ахапох тут как тут и не может удержаться от наставлений молодёжи на путь истинный, ведь он знает, как надо! Надо сказать: "Работай, блять!" и всё сразу заработает!

**Comment by AxapooH** [comment]
> О нет, суровый ахапох тут как тут и не может удержаться от наставлений молодёжи на путь истинный, ведь он знает как надо! Надо сказать: "Работай, блять!" и всё сразу заработает!

Ну типа у андроидов уже есть урон от эми встроенный. Но валера слепил хуйню, вместо подкрутки встроенной.

**Comment by Boroda2228** [comment]
> > О нет, суровый ахапох тут как тут и не может удержаться от наставлений молодёжи на путь истинный, ведь он знает как надо! Надо сказать: "Работай, блять!" и всё сразу заработает!
> 
> Ну типа у андроидов уже есть урон от эми встроенный. Но валера слепил хуйню, вместо подкрутки встроенной.

я конечно согласен с тем что баланс андроидов из крайности в крайность, но подвожу к мысли "критикуешь - предлагай", в конце-концов тебе виднее чем бы законтрить уместно

**Comment by AxapooH** [comment]
> > > О нет, суровый ахапох тут как тут и не может удержаться от наставлений молодёжи на путь истинный, ведь он знает как надо! Надо сказать: "Работай, блять!" и всё сразу заработает!
> > 
> > 
> > Ну типа у андроидов уже есть урон от эми встроенный. Но валера слепил хуйню, вместо подкрутки встроенной.
> 
> я конечно согласен с тем что баланс андроидов из крайности в крайность, но подвожу к мысли "критикуешь - предлагай", в конце-концов тебе виднее чем бы законтрить уместно

Я тебе только что сказал - увеличить урон от эми.
Хоть начнут им пользоваться.

**Comment by Boroda2228** [comment]
> > > > О нет, суровый ахапох тут как тут и не может удержаться от наставлений молодёжи на путь истинный, ведь он знает как надо! Надо сказать: "Работай, блять!" и всё сразу заработает!
> > > 
> > > 
> > > Ну типа у андроидов уже есть урон от эми встроенный. Но валера слепил хуйню, вместо подкрутки встроенной.
> > 
> > 
> > я конечно согласен с тем что баланс андроидов из крайности в крайность, но подвожу к мысли "критикуешь - предлагай", в конце-концов тебе виднее чем бы законтрить уместно
> 
> Я тебе только что сказал - увеличить урон от эми. Хоть начнут им пользоваться.

ты шиз блядь, где ты сказал "увеличить", лол. мы текстом общаемся, тут отследить кто пиздит легче лёгкого

**Comment by AxapooH** [comment]
> > > > > О нет, суровый ахапох тут как тут и не может удержаться от наставлений молодёжи на путь истинный, ведь он знает как надо! Надо сказать: "Работай, блять!" и всё сразу заработает!
> > > > 
> > > > 
> > > > Ну типа у андроидов уже есть урон от эми встроенный. Но валера слепил хуйню, вместо подкрутки встроенной.
> > > 
> > > 
> > > я конечно согласен с тем что баланс андроидов из крайности в крайность, но подвожу к мысли "критикуешь - предлагай", в конце-концов тебе виднее чем бы законтрить уместно
> > 
> > 
> > Я тебе только что сказал - увеличить урон от эми. Хоть начнут им пользоваться.
> 
> ты шиз блядь, где ты сказал "увеличить", лол. мы текстом общаемся, тут отследить кто пиздит легче лёгкого

Окей. От эти андроид, в зависимости от силы, получает 5-20 урона на все тело поджогом и стан в зависимости от силы. Увеличить до 40-80 за гранату 100 на 100 и все. Тот же путешитель, только стан дольше.
