### ISSUE TITLE
[IDEA] добавить големам возможность летать на их корабле

### ISSUE THREAD

**Issue by SanecMan** [frosty-dev/white#173]
Добавить возможность големам на их корабле летать. Плату для полётов нужно покупать за 5к очков в вендоре.

**Comment by TequilaSunrise272** [comment]
пошёл нахуй

**Comment by Gesugao-san** [comment]
Интересное предложение, но зачем? По лору их разослали, и они должны развивать жизнь там, куда их запустили, а не как рейнджеры летать по всему космосу

**Comment by RedFoxIV** [comment]
> 
> 
> Интересное предложение, но зачем? По лору их разослали, и они должны развивать жизнь там, куда их запустили, а не как рейнджеры летать по всему космосу

зис
А ещё тот факт, что их корабль на самом деле нихуя не корабль (со стороны кода), а просто домик в виде корабля. Плюс тот факт, что у них весь прогресс завязан на дрочке лаваленда.

**Comment by SanecMan** [comment]
> Интересное предложение, но зачем? По лору их разослали, и они должны развивать жизнь там, куда их запустили, а не как рейнджеры летать по всему космосу

Им сказали "Делайте чё хотите" а не "Развивайте жизнь"

**Comment by Gesugao-san** [comment]
> > Интересное предложение, но зачем? По лору их разослали, и они должны развивать жизнь там, куда их запустили, а не как рейнджеры летать по всему космосу
> 
> зис
> А ещё тот факт, что их корабль на самом деле нихуя не корабль (со стороны кода), а просто домик в виде корабля. Плюс тот факт, что у них весь прогресс завязан на дрочке лаваленда.

зис
Но корабль сделать из домика на Лаваленде функционирующим шаттлом — можно, эти механизмы расписаны и даже я могу попробовать (ключевое слово) это сделать, так что этот пункт нельзя называть нереализуемым...

---

> > Интересное предложение, но зачем? По лору их разослали, и они должны развивать жизнь там, куда их запустили, а не как рейнджеры летать по всему космосу
> 
> Им сказали "Делайте чё хотите" а не "Развивайте жизнь"

Допустим, я не углядел, и там действительно так, как ты говоришь, но я считаю, что здесь уже Рэд прав:
Големы играют от Лаваленда, и если мы хотим их оторвать от земли и отправить в космос, то нам нужно обосновать это какой-то причиной, например, добавить механики категории "late-game"'ма aka поздней игры, где для каких-то вещей требуются полёты в космос.. или даже на саму станцию 13. Но какие? Вот, в чём вопрос.

**Comment by RedFoxIV** [comment]
у нас лейтгейм на станции в 80% раундов начинается с состыковки эвакуационного шаттла и это до сих пор никто не может решить

**Comment by Gesugao-san** [comment]
> у нас лейтгейм на станции в 80% раундов начинается с состыковки эвакуационного шаттла и это до сих пор никто не может решить

Так это проблема или всем нормально так быстро сливать раунды?

**Comment by RedFoxIV** [comment]
> 
> 
> > у нас лейтгейм на станции в 80% раундов начинается с состыковки эвакуационного шаттла и это до сих пор никто не может решить
> 
> Так это проблема или всем нормально так быстро сливать раунды?

давай перефразирую:  у нас нет лейтгейма, чтобы делать контент для лейтгейма

**Comment by RedFoxIV** [comment]
> 
> 
> > Интересное предложение, но зачем? По лору их разослали, и они должны развивать жизнь там, куда их запустили, а не как рейнджеры летать по всему космосу
> 
> Им сказали "Делайте чё хотите" а не "Развивайте жизнь"

ну давай дадим всем големам по аплинку и свиточек телепорта, пусть набегают на станцию, если хотят, хули бля

**Comment by RedFoxIV** [comment]
протухло
