### ISSUE TITLE
[IDEA]дать артистам аплинк синдиката с бесконечными тк

### ISSUE THREAD

**Issue by MrDeni4** [frosty-dev/white#174]
Ну а что? На игру не повлияет, да и хорошая возможность протестить предметы.

**Comment by Necoachan** [comment]
он и так есть, ты дотянись до него

**Comment by MrDeni4** [comment]
Я это и сделал. Ну как, я передвинул автомат а аплинк повис в воздухе

**Comment by TequilaSunrise272** [comment]
а зачем тебе аплинк?

**Comment by MrDeni4** [comment]
А почему бы и нет? Хорошая возможность тестить триторский шмот в безопасной среде

**Comment by TequilaSunrise272** [comment]
хостишь локалку - тестиш триторский шмот

**Comment by MrDeni4** [comment]
А на локалке других игроков нет, да и билд у нас особенный

**Comment by TequilaSunrise272** [comment]
а чё особенного

**Comment by MrDeni4** [comment]
Фич много своих в коде. Интегралки, хохлокараси, чемоданы с деньгами поменяли

**Comment by MrDeni4** [comment]
Станбатоны

**Comment by TequilaSunrise272** [comment]
а чё мешает захостить и затестить?

**Comment by MrDeni4** [comment]
Первая причина - билд вроде закрытый, вторая причина - на локалке не будет других игроков

**Comment by jhnazar** [comment]
ХохлокарасЬ не фича. Это тупо респрайт магикарпа

**Comment by MrDeni4** [comment]
У него больше хп

**Comment by MrDeni4** [comment]
1488

**Comment by jhnazar** [comment]
Разрешаю понизить до 500

**Comment by TequilaSunrise272** [comment]
> Первая причина - билд вроде закрытый, вторая причина - на локалке не будет других игроков

так он открытый блядь, ты где пишешь по-твоему?

**Comment by MrDeni4** [comment]
Вторая причина?

**Comment by TequilaSunrise272** [comment]
> Вторая причина?

а че ты там тестить собрался, что требует кол-во игроков?

**Comment by MrDeni4** [comment]
Спящий карп на себе особо не затестишь

**Comment by TequilaSunrise272** [comment]
> Спящий карп на себе особо не затестишь

заспавни хумана

**Comment by MrDeni4** [comment]
Хуман не сможет ответить

**Comment by TequilaSunrise272** [comment]
> Хуман не сможет ответить

там есть hostile ИИ

**Comment by Gesugao-san** [comment]
Могу добавить.. кхм, @Valtosin, не против?

**Comment by RedFoxIV** [comment]
дайте прошаренному человеку дебаг аплинг и он крашнет сервер за 5 минут
дайте аплинк тупому и сервер рухнет через 3 минуты

Не надо.

**Comment by MrDeni4** [comment]
Я тут подумал, крашнуть сервер действительно возможно. Но в таком случае можно просто давать ограниченное число телекристаллов, например 100, или 200.

**Comment by RedFoxIV** [comment]
просто подними ёбаную локалку...

**Comment by MrDeni4** [comment]
Видишь ли, если бы такая мысль пришла в голову только мне, я бы так и поступил - запустил локалку. На локалке больше возможностей, можно тестить не только предметы из аплинка. Но, хотя я не сказал этого выше, такое введение разнообразит gayмплей (взаимодействие между артистами и не только). Серьезно, каждый второй человек, который заходил за артиста, предлагал мне помолиться чтобы нам дали световой меч или что - то в этом роде.

**Comment by RedFoxIV** [comment]
я этот ебучий аплинк добавил в качестве шутки, теперь меня заставляют его удалить нахуй
зачем?

**Comment by RedFoxIV** [comment]
> 
> 
> Видишь ли, если бы такая мысль пришла в голову только мне, я бы так и поступил - запустил локалку. На локалке больше возможностей, можно тестить не только предметы из аплинка. Но, хотя я не сказал этого выше, такое введение разнообразит gayмплей (взаимодействие между артистами и не только). Серьезно, каждый второй человек, который заходил за артиста, предлагал мне помолиться чтобы нам дали световой меч или что - то в этом роде.

какой блядь геймплей у артистов, всё, что там можно делать это дрочить механ в своём аутизмоуголке или пиздиться
что ты хочешь разнообразить?

**Comment by MrDeni4** [comment]
Вот именно! Как ты говоришь, "пиздиться" станет намного веселее

**Comment by RedFoxIV** [comment]
пиздиться тулбоксом против дебила в маулере нихуя не весело.
Подожду до завтра, если никто больше не впишется, закрою

**Comment by Gesugao-san** [comment]
@RedFoxIV го хотя бы обычный, для теста

**Comment by RedFoxIV** [comment]
аплинк с бесконечными ТС это пиздец какая сломанная вещь, чтобы давать её обычным игрокам

Если давать по аплинку каждому артисту, у них будет бесконечные аплинки.
Если давать аплинк только одному, будут срачи и дебилы, которые возьмут карп и не будут никого пускать на артистов и хуй ты чё с этим сделаешь.

**Comment by Gesugao-san** [comment]
> аплинк с бесконечными ТС это пиздец какая сломанная вещь, чтобы давать её обычным игрокам
> 
> Если давать по аплинку каждому артисту, у них будет бесконечные аплинки.
> Если давать аплинк только одному, будут срачи и дебилы, которые возьмут карп и не будут никого пускать на артистов и хуй ты чё с этим сделаешь.

то есть или выдать, и ограничить кол-во спавнов, или закрывать

**Comment by MrDeni4** [comment]
Можно добавить артисту в флавортекст не быть мудаком. Ну, какое - нибудь правило, которое запрещает спавнкемперить. Не давать играть можно и обычным тулбоксом, если игрок опытный.

**Comment by TequilaSunrise272** [comment]
или просто не ебать себе мозг и не выдавать аплинк лоол

**Comment by MrDeni4** [comment]
Так зачем тогда нужен канал suggestions?

**Comment by MrDeni4** [comment]
Ничего сложного нет в том, чтобы добавить одно предложение в флавортекст

**Comment by RedFoxIV** [comment]
#suggestions нужен, чтобы игроки делали suggestions

 
> > аплинк с бесконечными ТС это пиздец какая сломанная вещь, чтобы давать её обычным игрокам
> > Если давать по аплинку каждому артисту, у них будет бесконечные аплинки.
> > Если давать аплинк только одному, будут срачи и дебилы, которые возьмут карп и не будут никого пускать на артистов и хуй ты чё с этим сделаешь.
> 
> то есть или выдать, и ограничить кол-во спавнов, или закрывать

артисты задумывались, как тандердом для бедных, куда призраки могут заваливаться до конца раунда и заниматься там хуйнёй, но никак не могут взаимодействовать с остальной игрой. (а-ля ctf)
выдавать аплинки всем - крайне простой багарбуз и ёбля хоста
выдавать аплинки первым n артистам - спидранящие дебилы, которые будут покупать карта и не давать играть никому на неравных условиях
выдавать аплинки всем артистам и ограничить число спавнов - говнокостыль ради одной невнятной фичи, которая ломает изначальную задумку артистов

Короче, нет.

> Можно добавить артисту в флавортекст не быть мудаком. Ну, какое - нибудь правило, которое запрещает спавнкемперить. Не давать играть можно и обычным тулбоксом, если игрок опытный.

у нас и так педаляторов не хватает, чтобы за самой станцией следить, не говоря уже о коробке 9 на 9 на отдельном з-уровне.
И ещё ты просто охуенно сравнил тулбокс и свиточек карпа.
