### ISSUE TITLE
[IDEA] Динамичность

### ISSUE THREAD

**Issue by Gustekkus** [frosty-dev/white#175]
### Возможно идея говно, но думаю она может добавить онлайна и будет достаточно уникальной в ру сегменте

**Итак, вот мой пак идей:**

**Добавить динамичные шаттлы.** 
Любой игрок после истечения определённого срока может сесть на динамичный шаттл 4х3 и сьебаться со станции. Например, состояние станции 80%, синий код, шаттлы включились, игроки эвакуируются. Шаттл летит до ЦК на медленной скорости в течение 20 минут, выходит оповещение с ЦК, Тайлер Дерден покидает станцию на шаттле №8. Татор хватает соседний шаттл, догоняет его, вырезает цель. Или же человек спокойно долетает до ЦК, НЕ получает метакэш и его удаляет и гостает.

**Зачем это нужно?**
Станция частично очиститься от апатиков. Функционал перехвата найдет себе применение. Игрок сможет переродитья, об этом далее

**Добавить респавн.** 
У нас много педалей и они нихуя не делают. Пинаем педалей добавляем им работы. После смерти включается 10 минутный таймер после которого игрок добровольно отказывается от старого тела (мертвого) и может респавниться. Тут подключаются слоты персонажей и перспективная монетизация проекта. Старый слот мертвого персонажа блокируется и человек либо делает нового, либо выбирает из уже имеющихся персонажей. Всего человек может переродиться 3 раза (3 слота), слоты можно докупать, получая больше "перерождений". Педали будут активно следить за соблюдением правил и возможных метамстях. Старое тело прошлого персонажа, после отказа, постепенно разлагается и исчезает со станции ВМЕСТЕ С ВЕЩАМИ, если не было до этого помещено в морг, дабы избежать манчкинизма и лутинга с бывшего трупа. Так же после отказа от тела слот под работку освобождается и человек снова может играть, НО, он не может зайти на ту же самую работу в тот же самый отдел, в свободный слот может попасть либо новый человек либо такой же "перерожденец", сделано будет это дабы, происходила мертвых игроков от отдела к отделу, всегда будет всех хватать.

**Зачем это нужно?**
Это добавит больше динамики, игра станет более щадящей к случайным смертям, игроки станут меньше гореть с злых и плохих дядях на трейторах которые портят им аутизм и прочее прочее. Особенно это будет полезно для новичков и людей типа Амейза.

**Как это связано с предыдущим пунктом?** 
Человек устал, не умеет, не получается, случайно зашел на работу и прочие прочие причины, берет, улетает со станции, его гостает (без возможности летать, конечно же) он берет нового персонажа, заходит на другую работу

Еще один пример, на станции полный пиздец, человек устал, человеку нечего делать так-как все разьебано/нет тока, он садиться на шаттл, улетает, его гостает, он идет играть на гостролях

И последний пример, татор выпилил всю станцию и вместо 25 минутного ожидания шаттла, он улетает на маленьком и получает гринтекст.

**Comment by Gustekkus** [comment]
Жду пояснений почему идея говно

**Comment by Alexs410** [comment]
Можно заменить на возможность постройки в космосе emergency spacepod'a, который при отлете с вероятностью 20% взрываются. (Нахуй нам вообще спейсподы, если им почти никто не пользуется?)

**Comment by jhnazar** [comment]
По поводу шаттлов лучше сделать не оповещение, а татор итем или консоль коммандования на которой выводится кто находится на этом шаттле (учитывая вкл и выкл состояния сенсоров)

**Comment by Gustekkus** [comment]
отдельный татор айтем жирно делать, лучше к существующему прикрутить такую функцию

**Comment by RedFoxIV** [comment]
а как шаттл А будет догонять шаттл Б, если они одинаковые

**Comment by RedFoxIV** [comment]
> 
> 
> Можно заменить на возможность постройки в космосе emergency spacepod'a, который при отлете с вероятностью 20% взрываются. (Нахуй нам вообще спейсподы, если им почти никто не пользуется?)

лолол, валеру спрашивай, он эти чудовищные поды вводил
я даже не ебу, откуда он их взял, я поды видел только на гунах и там они не __настолько__ дерьмо

**Comment by Gesugao-san** [comment]
@Gustekkus Идея мне нравится, но лично я реализовать её вряд-ли смогу.

---
> Можно заменить на возможность постройки в космосе emergency spacepod'a, который при отлете с вероятностью 20% взрываются. (Нахуй нам вообще спейсподы, если им почти никто не пользуется?)

@Alexs410 Если **ты** не пользуешься подами, и не видишь, что там происходит, то это абсолютно не значит, что ими никто не пользуется.

---
> По поводу шаттлов лучше сделать не оповещение, а татор итем или консоль коммандования на которой выводится кто находится на другом шаттле (учитывая вкл и выкл состояния сенсоров)

@jhnazar Можно ввести отдельную консоль для этого или программу для модульного ПК.

**Comment by Gustekkus** [comment]
> а как шаттл А будет догонять шаттл Б, если они одинаковые

Емаг

**Comment by RedFoxIV** [comment]
> 
> 
> > а как шаттл А будет догонять шаттл Б, если они одинаковые
> 
> Емаг


>не купил емаг - соснул
лол, нет.

**Comment by RedFoxIV** [comment]
протухло

**Comment by Gesugao-san** [comment]
звучит интересно, но я как кодер не настолько силён, чтобы это сделать, поэтому можно пока просто отложить в долгий ящик

**Comment by HalilDaBlack** [comment]
Говно
