### ISSUE TITLE
Кошелёк и ID карта [BUG]

### ISSUE THREAD

**Issue by AldoDonkar** [frosty-dev/white#176]
## ID Раунда:
9487

## Как повторить?

Берёшь кошелёк
убираешь в него ID карту
она работает
убираешь в кошелёк деньги/другой предмет
внутри кошелька добавляешь на карту деньги /вынимаешь предмет
карта не работает, двери её не видят
пока карту не вытащишь/не вернёшь предмет, она не заработает
![image](https://user-images.githubusercontent.com/87540895/125987071-c87e0806-c6b6-42ba-86a8-7284016c1f25.png)

**Comment by Valtosin** [comment]
https://github.com/tgstation/tgstation/issues/58745

**Comment by Valtosin** [comment]
8f9499fff4dde0939c40ec27904fbde818e56947
