### ISSUE TITLE
[BUG] 2 проблемы с ящерами и 1 баг с квирком "поврежденный язык"

### ISSUE THREAD

**Issue by Bekoshka** [frosty-dev/white#177]
## ID Раунда:
9496

## Как повторить?
1 баг- Зайти за ящера и сказать "к". Отобразится "ксс", что странно, ведь к- не шипящий  звук
2 баг- зайти за ящера, выбрав "digitigrade legs" в настройке персонажа и описать себя. digitigrade будет описано как "искусственные ноги", хотя digitigrade- это животное, которое ходит на пальцах вместо пяток. можно хотя-бы убрать "искусственный?" странно выглядит просто.
3 баг- Зайти с квирком "поврежденный язык." и что либо сказать. отобразится что персонаж "поет", но....видимо переводчики перепутали signs (показывает знак) с sings (поет)

надеюсь я помогу развитию сервера...

**Comment by Blessedshruman** [comment]
Ящеры это мем-раса и всерьез их мелкопроблемами никто заниматься не будет)

**Comment by RedFoxIV** [comment]
проблемы ящероёбов

**Comment by RedFoxIV** [comment]
![tenor (2)](https://user-images.githubusercontent.com/38788538/127257645-76e3e5e0-a08c-4388-87ed-d2582772539b.gif)

**Comment by Bekoshka** [comment]
ладно

пн, 19 июл. 2021 г., 9:01 RedFoxIV ***@***.***>:
