### ISSUE TITLE
[BUG] Лоза в космосе

### ISSUE THREAD

**Issue by jhnazar** [frosty-dev/white#178]
## Как повторить?
Хз. Вижу что лоза в космосе. Кажись она на опентурфе может расти.
![image](https://user-images.githubusercontent.com/62169344/126034201-ffbb8620-aec3-41fa-89d5-c90e97b95aee.png)
![image](https://user-images.githubusercontent.com/62169344/126034211-91350d04-f893-4644-aba6-e02ea8106725.png)
![image](https://user-images.githubusercontent.com/62169344/126034216-f493f5e5-7c92-4b68-888a-477902429215.png)
Короче бля. Надо этим хуеглотам убрать имунн к космосу ещё, а то они убер ОПшные из-за этой хуйни, ДА!

**Comment by RedFoxIV** [comment]
заодно надо убрать эти диагональные лианы-хуяны, которые  остаются до конца раунда, никак не убрать и дамажат всех, кто пройдёт через них.

**Comment by Valtosin** [comment]
8f9499fff4dde0939c40ec27904fbde818e56947
