### ISSUE TITLE
[IDEA] Новый Эвакуационный Шаттл

### ISSUE THREAD

**Issue by Zavanick** [frosty-dev/white#1781]
![IMG_20221216_011135](https://user-images.githubusercontent.com/121029968/209070746-e198e7af-6ea8-408a-a3b8-6526ea662b62.jpg)
Всем привет, вот шаттл, не удивляйтесь почему на аве синдикат (у меня так моя команда называется)
Zavanick и его попытки пробиться в мапперы.
https://drive.google.com/file/d/1Pzvs8mzz6szNRasjaJQqok3iifJgqoZM/view?usp=sharing
не вирус
мой дс Zavanick#9037
фотка плохого качества, извините, но мой пк не готов потянуть 2 приложения + сервер.

**Comment by Boroda2228** [comment]
Я думаю раз ты пикчу не смог вставить, че тут еще можно добавить

**Comment by AxapooH** [comment]
Какой синдикат на аве, какой шаттл. Почему биновый файл в гуглдрайве, почему не пуллреквест через репозиторий со скрином из игры, ебана рот.

**Comment by Boroda2228** [comment]
Ещё такая милая пометка: "не вирус", пиздец просто

**Comment by GrishaGold** [comment]
Считаю что надо мерджить

**Comment by Zavanick** [comment]
> Я думаю раз ты пикчу не смог вставить, че тут еще можно добавить

если требуется, то фото приложу, момент.

**Comment by Zavanick** [comment]
> Какой синдикат на аве, какой шаттл. Почему биновый файл в гуглдрайве, почему не пуллреквест через репозиторий со скрином из игры, ебана рот.

потому, что не работает у меня.

**Comment by Boroda2228** [comment]
Спасибо за фото, братан, несколько замечаний:
1. Скриншот делается через кнопочку PrintScreen или на Windows 10 и выше через комбинацию клавиш "Win+Shift+S", далее вставляется в пейнт и обрезается ненужное, затем сохраняется в любом формате и отправляется сюда.
2. Этот репозиторий по SS13, а не SS14.
3. Всего Вам доброго!

**Comment by FelineMistress** [comment]
вы ошиблись адресом

**Comment by Zavanick** [comment]
> Спасибо за фото, братан, несколько замечаний:
> 
> 1. Скриншот делается через кнопочку PrintScreen или на Windows 10 и выше через комбинацию клавиш "Win+Shift+S", далее вставляется в пейнт и обрезается ненужное, затем сохраняется в любом формате и отправляется сюда.
> 2. Этот репозиторий по SS13, а не SS14.
> 3. Всего Вам доброго!

я ведь писал, что мой пк не может потянуть 2 программы + локальный сервер.

**Comment by Boroda2228** [comment]
И с каких пор твои проблемы = наши проблемы?
Хорошего дня!
