### ISSUE TITLE
[BUG] Зарядник револьвера

### ISSUE THREAD

**Issue by Zzwzzzz** [frosty-dev/white#180]
## ID Раунда: 9518

![Screenshot_17](https://user-images.githubusercontent.com/57303635/126076286-b93eb1b3-d754-45cb-9e66-4bcf5f226b64.png)

Просто не отображается в лапке, но работает.  /obj/item/ammo_box/magazine/internal/cylinder/rev357

**Comment by Zzwzzzz** [comment]
Если заметишь это, то дополню, что оно, оказывается, не кидается и не суётся в рюкзак.

**Comment by RedFoxIV** [comment]
>/internal/
