### ISSUE TITLE
[IDEA] Раз у полевого Медика отобрали Дефиб, дать ему Операционный компьютер как у Мед Борга

### ISSUE THREAD

**Issue by FelineMistress** [frosty-dev/white#182]
С операционным компьютером он станет настоящим полевым медиком, а не как сейчас мед который лечит брут и ожог но травит бедолаг. Сможет может быстро зашивать людей в поле и способен производить любые хирургические операции, если синхронизирован конечно. Подсказок эта штука не дает (настоящему хирургу они не нужны) и жизненные показатели не показывает, но хотя бы возможность есть. Для корректной работы ее нужно будет носить в кармане или на поясе. Если вам прям вооообще не жалко то сделать эту штуку заодно уникальным хирургическим поясом: носится на поясе + открывает операции + переносит предметы, но это имхо уже имба

**Comment by RedFoxIV** [comment]
>а не как сейчас мед который лечит брут и ожог но травит бедолаг.
у тебя в бронежилете 5 слотов, в самый раз, чтобы носить 4 химстакана на каждый вид урона и, по желанию, шприц

**Comment by TequilaSunrise272** [comment]
> > а не как сейчас мед который лечит брут и ожог но травит бедолаг.
> 
> у тебя в бронежилете 5 слотов, в самый раз, чтобы носить 4 химстакана на каждый вид урона и, по желанию, шприц

теперь нет

**Comment by RedFoxIV** [comment]
всмысле

**Comment by TequilaSunrise272** [comment]
> всмысле

я удалил

**Comment by RedFoxIV** [comment]
зачем

**Comment by TequilaSunrise272** [comment]
> зачем

уебищный спрайт от зергиверги был

**Comment by RedFoxIV** [comment]
одобряю

**Comment by FelineMistress** [comment]
удалять кармашки т.к. не нравится спрайт, окай... блин а такая удобная штука была. Серьезно все поотбирали, дайте ему Операционный Компьютер и Бог Баланса над вами смилостивится

**Comment by TequilaSunrise272** [comment]
> удалять кармашки т.к. не нравится спрайт, окай... блин а такая удобная штука была. Серьезно все поотбирали, дайте ему Операционный Компьютер и Бог Баланса над вами смилостивится

я не думаю что в броник должен помещаться батон

**Comment by FelineMistress** [comment]
в него не помещался батон, туда можно было положить только маленькие предметы, баночки с таблетками, фонарик, еще каталка почему то влезала

**Comment by Alexs410** [comment]
bump
