### ISSUE TITLE
[IDEA] Добавить перк "стрелок", который позволяет точно стрелять с двух рук

### ISSUE THREAD

**Issue by MrDeni4** [frosty-dev/white#183]

**Comment by Blessedshruman** [comment]
Ну щас еще перк ударник добавим, который позволяет станить кулаком в ебало..........

**Comment by RedFoxIV** [comment]
Раунд окончен.
Голова, глаза.

**Comment by MrDeni4** [comment]
Какой раунд? Какие глаза? Какой ударник?

**Comment by Blessedshruman** [comment]
Обычный ударник. Я тебе привел пример абсурдной фичи, которая точно так же сломает игровой баланс как твоё предложение.

**Comment by Gesugao-san** [comment]
> Какой раунд? Какие глаза? Какой ударник?

@MrDeni4 
раунд - она же смена

"Голова, глаза" - описание ранений хедшота в Таркове, мем такой
![image](https://user-images.githubusercontent.com/28023014/126441288-8e453cc2-966f-43dc-8c51-b9feae345bef.png)

про ударника уже сказано тут - https://github.com/frosty-dev/white/issues/183#issuecomment-883550057
перки можно настраивать при создании перса в лобби в соответствующем меню
