### ISSUE TITLE
[BUG] Автопривязка стазиса к консоли не работает.

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#184]
Автопривязка стазиса к консоли сломана. 
## Как повторить?
1. Построить стазис
2. Построить консоль для операций.
3. Понять что не работает
Или
1. Построить консоль для операций.
2. Построить стазис
3. Понять что не работает

**Comment by Valtosin** [comment]
Всё работает...
![](https://i.imgur.com/TEPyqxe.png)
