### ISSUE TITLE
[BUG] ГРАНАТА!

### ISSUE THREAD

**Issue by AxapooH** [frosty-dev/white#1843]
Короче граната биотеррора из набора синдикосского не работает. 
Там тупо нету воды для фторовой пены. Поэтому там вместо "БЛЯПАЦАНЫ!" просто Пшик. 
Ну и по хорошему сменить бы корпус гранаты с обычного на большой, потому что там 2 блюспейс стакана стоит.

**Comment by FelineMistress** [comment]
там есть вода, но она раундстартом реагирует с часоточным порошком и самовыпилывается, сейчас что-нибудь сделаю
