### ISSUE TITLE
[BUG] йохаи

### ISSUE THREAD

**Issue by Chilipila** [frosty-dev/white#187]
Монитор исполнения.
--------------------------------------------------------------------------------
Здесь выводятся задания. Стекло всё ещё выглядит не очень крепким...
--------------------------------------------------------------------------------
Задание: Захватить Неизвестный и доставить живьём в логово.
Награда: 10

Баланс: 0

## ID Раунда:
9623

## Как повторить?
тыкнул по консоли дало задание "Захватить Неизвестный"

**Comment by Valtosin** [comment]
Мем

**Comment by RedFoxIV** [comment]
валера, real_name

**Comment by Chilipila** [comment]
короче узнали в чём прикол...
ему отхуярили голову
