### ISSUE TITLE
[BUG] Всего лишь нужно

### ISSUE THREAD

**Issue by AxapooH** [frosty-dev/white#1889]
Из-за вас, скучающих и спящий пидоров, которые нихуя не отвечают на тикет и в дис, мне это ещё и репортить пока раунд идет. 
![изображение](https://user-images.githubusercontent.com/106828728/222490990-cf62e921-81aa-4552-aa99-6075cd061ffb.png)
![изображение](https://user-images.githubusercontent.com/106828728/222491028-9d80e9c1-32d6-4045-8418-13686bf4f8af.png)

**Comment by Valtosin** [comment]
должно быть исправлено
