### ISSUE TITLE
[BUG] Багорбалеты.

### ISSUE THREAD

**Issue by Alexs410** [frosty-dev/white#189]
https://github.com/frosty-dev/white/blob/master/white/valtos/code/makeshift/crossbow.dm

Те самые арбалеты, которые заряжаются стержнями, при попадании с третьего режима создают в теле НЕВЫТАСКИВАЕМЫЕ (включая админхилом)  погнутые стержни. /obj/item/bent_rod 
Не ебу, что в коде не так, но оно неправильно застревает.

**Comment by Valtosin** [comment]
Пофикшено
