### ISSUE TITLE
[IDEA] Нерф ЕРП-панели

### ISSUE THREAD

**Issue by RaShCat** [frosty-dev/white#190]
Хотелось бы убрать урон у ТАНЦЕВАЛЬНЫХ действий. Ибо какой-либо ревенант прилетает и происходит это:
![изображение](https://user-images.githubusercontent.com/33174229/126898105-4b6e059a-e6a1-4e37-916f-ed26c3fbe0d5.png)
Не круто.

**Comment by RedFoxIV** [comment]
затрахали насмерть

**Comment by TequilaSunrise272** [comment]
kjk

**Comment by Valtosin** [comment]
8f9499fff4dde0939c40ec27904fbde818e56947
