### ISSUE TITLE
[BUG] больной на голову вирус ломает силиконов.

### ISSUE THREAD

**Issue by FelineMistress** [frosty-dev/white#191]
недавний "шедевр" неких озабоченных лиц, полностью ломает Киборгов и по словам Валеры еще и ИИ. Все инструменты блокируются, улучшения вываливаются, батарея отключается, рация отключается, Роботакт ломается, даже Позитронка или мозг вываливаются наружу. Остается только движение и удаленка к шлюзам

**Comment by Valtosin** [comment]
ЧТО

**Comment by TequilaSunrise272** [comment]
не баг а фича (ТМ)

**Comment by Valtosin** [comment]
https://github.com/frosty-dev/white/commit/1d19006aeaa6e6f265102c5cb552151024d112c5
