### ISSUE TITLE
[BUG] Влияние от взрыва суперматерии

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#193]
## Суть
Во время взрыва материи люди облучаются, начинаются галлюцинации. Проблема в том, что это действует только на 2 з-уровне (где у нас это нижние техи), а на 3-з уровне (основном уровне станции) это просто игнорируется, вследствие чего людям не приходится искать укрытие, чтобы спастись от нежелательных галюнов и облучения.
Вопросы?

**Comment by RedFoxIV** [comment]
двумерные взрывы в двумерной игре

**Comment by Valtosin** [comment]
fixed
