### ISSUE TITLE
[BUG] Зомби голодают

### ISSUE THREAD

**Issue by Zzwzzzz** [frosty-dev/white#197]
Голод у зомби усиливается не так уж и быстро, но неумолимо, и даже 5 съеденных друг за другом пицц не понижают показатель с минимального, а когда пытаешься съесть, например, мясо или мозги, то персонаж только бьёт себя по лицу. Такое работает и с некоторыми другими предметами пищи, закономерности между которыми не нашла.

**Comment by RedFoxIV** [comment]
ну вот и фикси давай, хотя бы пользу принесёшь вместо 9000 одинаковых ботинок

**Comment by Valtosin** [comment]
странная хуйня, воспроизвести не получилось, нужно больше информации

**Comment by TequilaSunrise272** [comment]
возник вопрос
