### ISSUE TITLE
[BUG] Невозможно таскать тела с одного з-уровня на другой

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#203]
## Суть
Нельзя перетаскивать тела/трупы сверху вниз, или снизу вверх без использования лестницы. Это создает большие проблемы с перевозкой тела, если, например, петух лежит в нижнем уровне в космосе. Приходится тогда через полстанции таскаться за ближайшей лестницей.
Пофиксите плз.

**Comment by TequilaSunrise272** [comment]
ты чё блядь

**Comment by Chilipila** [comment]
псих?
там где можешь залезть сам, туда можно затащить и тело

**Comment by TequilaSunrise272** [comment]
нельзя нихуя блядь

**Comment by Chilipila** [comment]
а ебать я псих
я понял про что
вы о стрелочках?

**Comment by RedFoxIV** [comment]
чипилла нихуя не понял, чипиллу никто не спрашивал, но он всё равно пердит что-то своё

**Comment by Chilipila** [comment]
с тобой тоже самое)

**Comment by Chilipila** [comment]
сам на всех лезешь, а потом плачешь "на вайте, без станбатона никуда"

**Comment by RedFoxIV** [comment]
не перди

**Comment by Chilipila** [comment]
https://discord.com/channels/433622753350778890/860328600011931648/872962241727713290 иди нахуй!

**Comment by Chilipila** [comment]
мамкин эдитор)

**Comment by RedFoxIV** [comment]
too heated
