### ISSUE TITLE
[BUG]Секботы считают оружием флораган

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#208]
Секботы считают за оружие цветочный луч ботаника(/obj/item/gun/energy/floragun), теоретически он в категории оружия, но по факту он не пушка.
## ID Раунда:

9880
## Как повторить?

Спавним кастратуса, берем в руки флораган за ассистуху и смотри на то, как тот пытается нас арестовать

**Comment by FelineMistress** [comment]
вообще это очень в стиле праобраза ed-209 :D, тот тоже считал опасным все, что хоть отдаленно напоминало ствол. Но смех смехом, а это правда странно.

**Comment by Valtosin** [comment]
Флораган летален
