### ISSUE TITLE
[BUG]Борги в клоункаре

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#209]
Борги могут спокойно сломать клоункар, находясь внутри. Просто инструментами долбить
Борги могут блокировать двери и электризовать их в клоункаре, это не должно так работать.
## ID Раунда:

9915
## Как повторить?

Залезаем за борга в клоункар и не чувствуем скованности, ломаем клоункар встроенным ломом и болтируем двери.

**Comment by RedFoxIV** [comment]
>Борги могут блокировать двери и электризовать их в клоункаре, это не должно так работать.

с чего это

**Comment by Chilipila** [comment]
Просто не жри боргов, и по сути если у тебя есть натидроп, ты тоже можешь ломать машинку изнутри

**Comment by Valtosin** [comment]
Не баг
