### ISSUE TITLE
[BUG] Нехватка коробок для торуса. Проблема с маппингом.

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#211]
![image](https://user-images.githubusercontent.com/44509388/129147725-fa30eeba-cdd8-423e-bd37-35652d70800b.png)

Не хватает углов торуса. Не баг, а просто не хватает 1 угла торуса, чтобы его можно было сразу сделать. Валера добавил, но не до конца...
## Как повторить?

1. Зайти в  Инженерный: Внешний доступ к суперматерии (лмао, там где поды делаются).
2. Посчитать кол-во углов.
3. Понять что не хватает.

**Comment by Valtosin** [comment]
фиксед
