### ISSUE TITLE
[IDEA] увеличение кала

### ISSUE THREAD

**Issue by LapSha1** [frosty-dev/white#216]
Увеличить колличество реагента говно в самом говне

Сейчас фекалии взрослого человека хватает на одну десятую стакана, требуется увеличить колличество говна хотя-бы до 20 юнитов

**Comment by RedFoxIV** [comment]
no

**Comment by LapSha1** [comment]
> no
why

**Comment by RedFoxIV** [comment]
нахуй тебе говно в стакане

**Comment by LapSha1** [comment]
Говорить попей говна

**Comment by RedFoxIV** [comment]
ладно
