### ISSUE TITLE
[IDEA]Лом

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#219]
Научить лом не отрывать плитки на харме. Неудобно, что после боя с использованием лома часть плиток отковыряло.
Пусть взаимодействие с плитками происходит лишь на хелпе

**Comment by RedFoxIV** [comment]
не используй лом в качестве оружия...

**Comment by Valtosin** [comment]
будет тебе

**Comment by Valtosin** [comment]
https://github.com/frosty-dev/white/commit/6cd9d831eb5de91d73032ff504c776e298d96270
