### ISSUE TITLE
[BUG] индустриальная сварка не разкручивается

### ISSUE THREAD

**Issue by LapSha1** [frosty-dev/white#223]
## Как повторить?
 Тыкнуть отвёрткой по сварке, откачать от туда топливо шприцом, залить плазму, закрутить, сварка взрывается.
Попробовать повторить на индустриальной сварке которую наверняка кто-то подберёт с пола если увидит, провалится на шаге 1

**Comment by LapSha1** [comment]
Блять что

**Comment by RedFoxIV** [comment]
сначала думай, потом пиши

**Comment by LapSha1** [comment]
> сначала думай, потом пиши
Думал, подумал что обидно что троллинг сваркой сломан

**Comment by LapSha1** [comment]
> чёт не заметно

Описал достаточно понятно, обычную сварку можно раскрутить отвёрткой а индустриальную нет, чини

**Comment by RedFoxIV** [comment]
ты описал невнятную хуйню

>чини

плати

**Comment by Chilipila** [comment]
Заплатил мне 500 и тогда я заплачу 250

Стонкс

**Comment by RedFoxIV** [comment]
чё

**Comment by Valtosin** [comment]
технически не баг
