### ISSUE TITLE
[BUG] Крысы грызут провода через рюкзак

### ISSUE THREAD

**Issue by LeShprotina** [frosty-dev/white#224]

**Comment by Valtosin** [comment]
А где баг

**Comment by LeShprotina** [comment]
Надо чтобы крысу, даже сквозь рюкзак било током. И того кто её положил к себе, тоже. Либо сделать так, чтобы она вообще не могла так делать. Как эта хвостатая тварь в полу-метре от пола грызёт провода, будучи в рюкзаке?

**Comment by Valtosin** [comment]
Не баг. Мышь погибает при укусе, хоть и незаметно.
