### ISSUE TITLE
[BUG] L6 Saw невозможно починить

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#225]
Пилу нельзя починить когда она заклинила
## Как повторить?

1. Взять L6 Saw
2. Стрелять пока не заклинит
3. ПКМ на неё открывает крышку, но не чинит пилу...

**Comment by RedFoxIV** [comment]
![image](https://user-images.githubusercontent.com/38788538/130352702-a6154315-4e18-4ec9-8782-84e7134c229a.png)

**Comment by Valtosin** [comment]
2989b5da54f87bf8de63f685652238593b568cb6
