### ISSUE TITLE
[BUG] Проблема с запуском локального сервера

### ISSUE THREAD

**Issue by Emanuserr** [frosty-dev/white#226]
Пытаюсь запустить локальный сервер. Нажимаю на BUILD.bat. Yarn, tgui и tgfont компилируются нормально, но dm постоянно выдаёт ошибку. Как решить эту проблему?
![Беда](https://user-images.githubusercontent.com/89359562/130370005-242ace84-fc37-4960-841e-9ecd099312c3.png)
 

## Как повторить?
Неизвестно

**Comment by RedFoxIV** [comment]
>514.1556
>1556

вам сюда http://www.byond.com/download/

**Comment by Valtosin** [comment]
Минимальная версия на данный момент это 514.1560
