### ISSUE TITLE
[BUG] Все эмбиенты зацикливаются

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#232]
Эмбиенты, которые должны одноразово проигрываться (всякие ambigen там, прочая хуйня), почему-то теперь имеют свойство каждый раз повторяться.
Я хуй знает, где это фиксить и появилось это по сути недавно, поэтому я мастурбирую яйцами и ввфббббббббдмымхххххххххххххххххххххххххххххххх

**Comment by Valtosin** [comment]
зафикшено
