### ISSUE TITLE
[BUG]У ЕРТшников нет навыков

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#233]
У ЕРТшников нет навыка стрельба, у медиков-ЕРТшников нет навыка медицины.
Смешно видеть, как спецназ пытается попасть по человеку в 5 метрах и мажет 30 выстрелами.
## ID Раунда:

10227
## Как повторить?

Зайти за спецназ

**Comment by TequilaSunrise272** [comment]
это у всех ролек и антагонистов в том числе

**Comment by RedFoxIV** [comment]
https://www.youtube.com/watch?v=eBhh23-paLU

**Comment by Valtosin** [comment]
fixed
