### ISSUE TITLE
[BUG] Спрайты повесились у термомашин. Сломана антиматерия.

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#234]
![image](https://user-images.githubusercontent.com/44509388/132211780-9c82e8c7-f80e-400b-a409-5235d9808397.png)
Проблема А. Спрайт термомашин сдох. 
Проблема Б. Антимать нельзя включить.
## Как повторить?

А. 1. Сделать термомашину.
2. Увидеть то, что её не видно.
Б. 1. Сделать антиматерию.
2. Засунуть туда топливо.
3. Посмотреть на прикол.

**Comment by Valtosin** [comment]
зафикшено
