### ISSUE TITLE
[BUG]Гейтвей и тюрьма Ромашка

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#240]
В гейтвее с тюрьмой ромашка сломались доступы, ключи не открывают ни одному дверь, доступа нема.
И угольный генератор с новой системой энергопотребления не справляется со своей задачаей
## ID Раунда:

10346
## Как повторить?

Подгружаем гейт, заходим за механика, начальника, вообще любого, кто должен иметь доступы.

**Comment by Valtosin** [comment]
> ключи не открывают ни одному дверь

пофикшено

> не справляется 

справляется, проверил
