### ISSUE TITLE
[BUG]Водичка

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#241]
Бармен только что налил воду из раздатчика, она по одной сотой начала превращаться в лед и булькать. Может это и не баг, но меня эти бульканья ежесекундные раздражают
[
![image](https://user-images.githubusercontent.com/88589686/133430798-12a7233e-e158-4f91-b71d-19e09da0872a.png)
](url)
## ID Раунда:

10346
## Как повторить?

Наливаем воду из раздатчика.

**Comment by RedFoxIV** [comment]
холодно
