### ISSUE TITLE
[BUG]пИИ раздевающий

### ISSUE THREAD

**Issue by Fesiks** [frosty-dev/white#242]
пИИ в форме голограммы может раздевать людей 

## Как повторить?
Гений заходит за пИИ и снимать может всё

**Comment by TequilaSunrise272** [comment]
ебать он охуел

**Comment by Chilipila** [comment]
А что не так? Если это не нарушает его законы...

**Comment by TequilaSunrise272** [comment]
а голограмма как раздевает?

**Comment by Chilipila** [comment]
А как пули дамадат голограмму?

**Comment by TequilaSunrise272** [comment]
как нехуй
