### ISSUE TITLE
[BUG] Хайджек ИИ за госта

### ISSUE THREAD

**Issue by GUDmood** [frosty-dev/white#245]
Оболочки ИИ и само ядро ИИ во время управления оболочкой, видны в меню перерождения как апатики и за них возможно зайти.
## ID Раунда:

10429
## Как повторить?

>У ИИ 2 оболочки 
>ИИ исользовал первую оболочку 
>Переключился на вторую
>Первая оболочка и ядро ИИ видны в меню перерождения
>Возможно зайти за обоих 
>Если оригинальный ИИ переключится на оболочку/ядро ИИ где поселился гост его выбрасывает из тела

**Comment by RedFoxIV** [comment]
валтос сучий чёрт
