### ISSUE TITLE
[BUG] нтнет плата говна

### ISSUE THREAD

**Issue by Chilipila** [frosty-dev/white#248]
плата нтнет из схамопринтера не передаёт (или не принимает хз честно) информацию

10454

в схемопринтере делаем хрень, в одной трансмиттер, в другой рессивер
результат: ничего не передаётся

**Comment by RedFoxIV** [comment]
![1535748610156823704](https://user-images.githubusercontent.com/38788538/134746955-498f3367-c534-4f0e-a6c1-48084ad914df.png)
