### ISSUE TITLE
[BUG]DAUN

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#252]
### Сборник говна с Dawn.

- В РнД нет той хуйни из роботики, что позволяет их создавать.
- В РнД нет холодильной камеры для слаймов

![image](https://user-images.githubusercontent.com/88589686/134976539-e95182ba-628f-465c-bab5-4208526d5982.png)

- В РнД нет устройства для теоретического расчета взрыва

![image](https://user-images.githubusercontent.com/88589686/134976607-5850c46c-2b69-4bca-85ef-cc9e2662d7e8.png)

- Генетика перешла в медбей, а вот доступа генетикам туда не дали

![image](https://user-images.githubusercontent.com/88589686/134976453-b3690170-61c2-4e22-878b-88f6f5bcbb64.png)

- Бар потерял раздатчик бухлишка

![image](https://user-images.githubusercontent.com/88589686/134976850-d2bb57ee-89d4-42e0-950b-dd2647b8ed2e.png)

- Шкафчики офицеров в бриге лишились поясов со станбатонами

![image](https://user-images.githubusercontent.com/88589686/134977049-09698c51-971f-4172-8add-90ba64d729e3.png)

- Главы лишились своих шкафчиков, я бы поставил их на мостик в ряд, каждый под плиткой покрашенный в цвета своего отдела

- Спутник ИИ не подключен к общей сети -> энергия рано или поздно закончится, для аутичной карты сидеть без связи и гравитации дело не допустимое

![image](https://user-images.githubusercontent.com/88589686/134977597-e8b3b8dc-0d3e-4ac2-b0cb-99825457724a.png)

## ID Раунда:

10483
## Как повторить?

Загрузить Dawn

**Comment by RedFoxIV** [comment]
кто маппил

**Comment by ThereDrD0** [comment]
Либо Валера, либо пендосы
