### ISSUE TITLE
Целая сборка найденных мной багов [BUG]

### ISSUE THREAD

**Issue by GrishaGold** [frosty-dev/white#253]
1. Если какая то вещь закреплена на руке имплантом то если оторвать руку и взять эту вещь то она прилипнет к руке.
2. SPECEPOD ROOM именуется как Инженерный: Внешний доступ к суперматерии 1
3. У Syndicate Man-Machine Interface нет нелегальных технологий.
4. На "Астероидах" либо нет астеройдов либо это пустое поле песка с растениями.
5. При событии "звездный свет" если посмотреть на космос не даёт баффа к настроению а хотелось бы. 

## ID Раунда:
10470-10489

## Как повторить?
Ну тут у разного по разному нужно проверить всё.

**Comment by FelineMistress** [comment]
5 вроде как не работает потому что бокс двухэтажный

**Comment by GrishaGold** [comment]
Раунд 10842.
6. Голопаразит не работает. Пишет:
You start to power on the injector...
...ERROR. BOOT SEQUENCE ABORTED. AI FAILED TO INTIALIZE. PLEASE CONTACT SUPPORT OR TRY AGAIN LATER...

**Comment by FelineMistress** [comment]
это вообще не баг, что ты кидаешь даже не разобравшись - это значит, что гостов или нет или все госты отказались от предложения стать голопаразитом
![2021-10-30_20-20-58](https://user-images.githubusercontent.com/87654572/139542941-aceb7b98-1b4b-498c-b189-67e52387d5f3.png)
А пишет в стилистике ИИ потому что это технократический тип, там же даже написано TRY AGAIN LATER

**Comment by GrishaGold** [comment]
"это значит, что гостов или нет или все госты отказались от предложения"

Во первых Госты были. Во вторых оно мгновенно после использования писало это.

**Comment by GrishaGold** [comment]
Я использую её и мгновенно пишет что не инициализируется ничего.

**Comment by FelineMistress** [comment]
Может это относится к багам спавнеров, хотя я заходил за голопаразита пару дней назад без ошибки
