### ISSUE TITLE
[BUG] полный, абсолютный, смехпиздец

### ISSUE THREAD

**Issue by Chilipila** [frosty-dev/white#256]
призраки могут управлять ускорителем частиц...

10494

умираем, тыкаем на кнопочки в ускорителе, настройки ускорителя частиц меняются

**Comment by RedFoxIV** [comment]
все взаимодействия с obj/machinery/ имеют проверку на то, жив ли вообще взаимодействующий.
либо кто-то недавно проебал проверку в родительском классе, позволяя призракам ралиплеить полтергейстов, либо валера что-то накрутил в ускорителе

**Comment by Chilipila** [comment]
я прямо сейчас тыкаю настройки ускорителя в госте

**Comment by Chilipila** [comment]
скорее всего проблема именно в ускорителе, потому что на других предметах это не работает
