### ISSUE TITLE
Про Йохеев (имба которую все не любят) [BUG]

### ISSUE THREAD

**Issue by GrishaGold** [frosty-dev/white#257]
Репутация у Йохеев тратится после конца раунда из за этого они не могут "РЕЗНЯ! РЕЗНЯ!" как все остальные :(

## ID Раунда:
10500

## Как повторить?
Взять Йохея и убить кого-то в конце рануда.

**Comment by RedFoxIV** [comment]
>[BUG]
![image](https://user-images.githubusercontent.com/38788538/135310172-f31ba731-ac86-4eb7-a2ae-7fedd612bcd7.png)
]

**Comment by FelineMistress** [comment]
это то ладно, но вот еще йохеи могут получить награду после конца раунда если во время "РЕЗНЯ! РЕЗНЯ!" грохнут их цель

**Comment by GrishaGold** [comment]
Ну как могут... пук среньк цель на украсть кого то и всё :+1:
