### ISSUE TITLE
Поды блять[BUG]

### ISSUE THREAD

**Issue by GrishaGold** [frosty-dev/white#258]
Пассажир пода если не в наручниках не может выйти из пода самостоятельно...

## ID Раунда:
10501

## Как повторить?
Пусть кто то сядет в под а вы за следом чтобы он был за рулём. И попытаться выйти из пода...

**Comment by FelineMistress** [comment]
это не баг, там пассажир в принципе выйти сам не может, для того чтобы его высадить надо самом толи кликнуть на под в режиме граба или дизарма толи перетащить на себя

**Comment by RedFoxIV** [comment]
изначально валерофичи были исключительно на его локальном билде, но потом он случайно прожал мерж и отказывается признаваться

**Comment by Fesiks** [comment]
Больше не фича, "починил" на локалке
