### ISSUE TITLE
[BUG] Баги с плейсментом, генерацией гейтов

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#259]
При спавне гейт-миссий через load away mission после начала раунда они появляются с проводами наружу и без света(Пример snowcabin.dmm или chilly.dmm)
![image](https://user-images.githubusercontent.com/44509388/135316549-1b0484dd-170e-4183-8a28-12c2b55fc44e.png)
![image](https://user-images.githubusercontent.com/44509388/135316663-0bc2c826-466b-4d15-b88a-76632be16cd1.png)
У шаттлов иногда отлетает привязка к зонам вместе со светом. К примеру при раскрытии DIY шаттла.
![image](https://user-images.githubusercontent.com/44509388/135316549-1b0484dd-170e-4183-8a28-12c2b55fc44e.png)
## Как повторить?

1. Нажимаем load away mission в вкладке События и загружаем гейт. 
2. Видим что провода вылезают из-под плиток вместе с трубами.
DIY шаттлы.
1. Берем блюспейс капсулу.
2. Раскрываем в космосе.
3. Видим сломанную консоль шаттла у обоих вариантов.

**Comment by Erring** [comment]
Упс, скриншот исчез с шаттлом. 
![image](https://user-images.githubusercontent.com/44509388/135325329-b11c8b08-aca3-44c2-bcc7-60b4f2a7fe87.png)

**Comment by RedFoxIV** [comment]
@Valtosin Valtosin self-assigned this on Sep 30, 2021
ичё
