### ISSUE TITLE
Перчатки СЕ и стансферы[BUG]

### ISSUE THREAD

**Issue by GrishaGold** [frosty-dev/white#260]
Резиновые Перчатки Старшего инженера не помогают если трогать ими стан сферы.

## ID Раунда:
10508
## Как повторить?
Надеть перчатки СЕ и потрогать стан сферу.

**Comment by RedFoxIV** [comment]
Ещё один высер по поводу "АЫАЫАЫ БАГИ КОКОК НЕ ФИКСЯТ БИЛД АЫА" и я начну считать тебя долбоёбом. Я считал ты нормальный и это уже не смешно. Почему ты так обосрался?

**Comment by Blessedshruman** [comment]
Так и надо
