### ISSUE TITLE
[BUG] парочка багов касающихся схемотехники

### ISSUE THREAD

**Issue by GUDmood** [frosty-dev/white#261]
1. Вкладка схемотехника пустая (через поиск компоненты находит)
2. Нет технологии Brain-Computer Interfaces, в коде компоненти есть (BCI Action, BCI Target Interceptor, ...) а технологии для открытия нет.
## ID Раунда:

10515
## Как повторить?

1. Открыть вкладку "Схемотехника" в любом протолате или принтере плат.
2. В Консоль R&D зашел, нужную технологияю не нашел.

**Comment by GUDmood** [comment]
К теме схемотехники, что то не так с названием компонентов NTNet
https://github.com/frosty-dev/white/blob/727f19542ecd69411001cea9ed084110f19c82f5/code/modules/research/designs/wiremod_designs.dm#L237
https://github.com/frosty-dev/white/blob/727f19542ecd69411001cea9ed084110f19c82f5/code/modules/research/designs/wiremod_designs.dm#L242
Аналог с ТГ 
name = "NTNet Transmitter"
name = "NTNet Receiver"

**Comment by GUDmood** [comment]
@Valtosin второй баг все еще с нами. Вроде как нехватает только ноди. 
ТГ референс: https://github.com/tgstation/tgstation/pull/60503/files#diff-0186fb83c12cba82db61a9185abfbaf220c7ce66663aefff6fb14baf6fccaee3

**Comment by Valtosin** [comment]
хз, проверишь, вроде всё теперь на месте
