### ISSUE TITLE
[IDEA] маскировка йохея

### ISSUE THREAD

**Issue by Chilipila** [frosty-dev/white#265]
вместо полной и абсолютно неюзабильности маскировки (сейчас), сделать так что-бы в инвизе ты не мог стрелять и бить, но был почти полностью невидим (ник тоже если возможно)

**Comment by Valtosin** [comment]
ммм чилипилки

**Comment by Blessedshruman** [comment]
Ураа награда за кодинг ломающих смысл игры фич
