### ISSUE TITLE
Копья в коленях[BUG]

### ISSUE THREAD

**Issue by GrishaGold** [frosty-dev/white#268]
Если кинуть копьё в какую то часть тела которую можно оторвать и оно там застрянет а потом оторвать то копья пропадут. ХОП ХА!

## ID Раунда:
10612

## Как повторить?
Кинуть Ершову в колени копья а потом оторвать обе ноги.

**Comment by GrishaGold** [comment]
Так понятнее?

**Comment by RedFoxIV** [comment]
не кидай копья если тебе их жалко потерять
