### ISSUE TITLE
[BUG]Призыв

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#277]
Боты не приходят на место призыва с помощью ПДА, где бы бот или человек не стояли.
![image](https://user-images.githubusercontent.com/88589686/137594753-3069761e-5576-4687-8f90-4af4b4fcf46a.png)

## ID Раунда:

10682

## Как повторить?

Призовите любого бота, он пошлет вас нахуй

**Comment by RedFoxIV** [comment]
троллинг уклонением от призыва
