### ISSUE TITLE
[BUG]Сигналер убил ноутбук

### ISSUE THREAD

**Issue by Fesiks** [frosty-dev/white#296]
Если скачать программу сигналера на ноутбук(с планшетом не проверял) и запустить её без модуля сигналера в устройстве то ноутбук умирает намертво
![image](https://user-images.githubusercontent.com/89092802/138269600-f406edc1-eace-4bd5-812c-cb4842f12993.png)

## ID Раунда:

10732

## Как повторить?

Скачайте программу сигналера на ноутбук и запустите без сигналера

**Comment by RedFoxIV** [comment]
скачал вишмастер
