### ISSUE TITLE
[BUG] свет в космосе

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#344]
Примерно недавно я заметил, что с освещением в космосе творится какая-то хуйня.

Например, КилоСтанция, где к станции прикреплены куски астероидов и эти самые астероиды имеют полное освещение, в отличие от самой станции, из-за чего можно увидеть подобные артефакты как на скрине ниже.
На них используется зона /area/space/nearstation
![image](https://user-images.githubusercontent.com/27878805/140639206-e94acff9-6d83-453f-8313-a86d62fbded3.png)

Однако я заметил, что на коробке в космосе не полностью прорисовывается освещение (в прибытии, как пример), хотя используется та же зона /area/space/nearstation
![image](https://user-images.githubusercontent.com/27878805/140639402-74d6daf3-0c4d-4e0a-bacd-b43e3dc92705.png)
![image](https://user-images.githubusercontent.com/27878805/140639405-24beb7e9-0aa1-481d-ae29-7beabcaf8d48.png)
![image](https://user-images.githubusercontent.com/27878805/140639432-a185d3b7-7ff7-478a-8974-c7f87e869f14.png)

Так как валерий валтосинов мне нихуя не сказал, а сам я понятия не имею, как это работает и на хуй оно нужно, я считаю своим долгом высрать это в качестве иссуя на гитхаб, пока или валера сам не починит, или не скажет, как это сделать

**Comment by Valtosin** [comment]
яйца

**Comment by TequilaSunrise272** [comment]
ты блядь нахрен

**Comment by Valtosin** [comment]
нужно вырубить свет у nearstation, так как у нас есть свет от космоса и так

**Comment by Valtosin** [comment]
@TequilaSunrise272 камс

**Comment by TequilaSunrise272** [comment]
ну я и отрубал у зоны, только все равно какова та хуя светило, я думал может это ты чето нахуевертить решил

**Comment by Nervol** [comment]
Я срал тебе в душу. Жидко гадил.

**Comment by TequilaSunrise272** [comment]
съебал под шконку

**Comment by Nervol** [comment]
> съебал под шконку

stick finger

**Comment by Valtosin** [comment]
хуй их знает, фиксов не нашёл пока
