### ISSUE TITLE
[BUG] Спелл рода гибает

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#369]
При использовании спелла превращения в род волшебника гибает, если он находится в стене в момент трансформации из рода обратно в человека.
## Как повторить?
Взять спелл рода, ПОЛЕТЕТЬ ПО ДИАГОНАЛИ (если лететь по вертикали или диагонали, то не гибнет), если действие спелла прекратилось в момент, как ты оказался в стене, тебя гибнет без какого-либо сообщения.

**Comment by GrishaGold** [comment]
Наконец это кто то сделал. Спасибо. Часто встречаюсь с этим багом и уже многие маги так умерали.
