### ISSUE TITLE
[BUG] В CryNet костюме нельзя есть/пить/срать

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#373]
## Суть
Костюм крайнета превращается из имбы в дебафф из-за того, что в костюме не можешь утолить жажду, утолить голод или справить нужду, в будущем испытывая огромные штрафы на муд, срезающие мобильность и скорость действий.
В теории, раз костюм снимать нельзя, дать возможность хотя бы срать через костюм или вкалывать себе инъекции с нутриментами или водой.

**Comment by RedFoxIV** [comment]
всмысле срать нельзя

**Comment by LapSha1** [comment]
Я запретил

**Comment by TequilaSunrise272** [comment]
в прямом

**Comment by Nikitauou** [comment]
Я запрещаю вам срать

**Comment by Fesiks** [comment]
ултра старо и неактуално
