### ISSUE TITLE
[BUG] Жажда

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#374]
Жажда не работает, как задумано.
Во-первых, жажду утоляет лишь сам реагент воды, в то время как нет реакций от других жидких реагентов типо газировки, чая, кофе, соков и т.д и т.п
Я чекал код утоления жажды, охуел и закрыл обратно, поэтому думаю, что это говно в идеале стоило бы переписать, с возможностью поддержки других реагентов.
Есть идея замутить это с помощью list() и приравнять реагенты к значениям жажды, но я хз как.

**Comment by daxsc** [comment]
fixed
