### ISSUE TITLE
[BUG] Секвей и титановый щит

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#375]
Титановый щит имеет огромный шанс блока, в то время срезающий скорость.
Если сесть на секвей или секвей уборщика, то скорость становится нормальной.
Не особо хорошо выглядит в плане баланса.

## Как повторить?
Взять в руки щит, испытать медленную скорость, сесть на секвей и превратиться в катающуюся имбу.

**Comment by RedFoxIV** [comment]
та же хуйня на оффтг, только с кэпским ригом и самокатом
https://youtu.be/KY1IPZv5y1k?t=85

проблема титанового щита в том, что он существует и срезает значимость разницы в робусте в 10 раз, хуже, чем вышеупомянутый риг
