### ISSUE TITLE
[IDEA] Оповещение о полученной рольке

### ISSUE THREAD

**Issue by TequilaSunrise272** [frosty-dev/white#380]
Писать обжективы и выдавать сообщение игроку о том, что он предатель или генокрад через 10-20 минут после начала раунда.

На остальных антагов это не применяется, если это не имеет необходимости (нюкеры, маги, ганги, революционеры и т.д)

**Comment by RedFoxIV** [comment]
а в чём разница, увидят ли они список задач в чате или в нотесах

**Comment by TequilaSunrise272** [comment]
не увидят нихуя

**Comment by Nikitauou** [comment]
ДА Я ЖЕ АГЕНТ СИНДИКАТА!
Это сообщение на весь чат вылетает, БОЛЬШИМИ ТАКИМИ КРАСНЫМИ БУКВАМИ, его трудно не заметить
