### ISSUE TITLE
[BUG] в меню кандидата ПИИ сломана кириллица  

### ISSUE THREAD

**Issue by Xrenoid** [frosty-dev/white#385]
в меню выбора описаний для самого ПИИ сломана киридлица https://media.discordapp.net/attachments/891936642380759050/914234506540630066/unknown.png
## Как повторить?

ну нажимаешь на кнопку КАНДИДАТ В ПИИ, сохраняешь хуйню, которую написал - готово блядь, почему я ради каждой первой тупой сломанной хуйни должен писать на гитхаб

**Comment by Xrenoid** [comment]
ой блядь проджект хреноид пользуется гитхабом

**Comment by TequilaSunrise272** [comment]
потому что о каждой сломанной хуйне можно забыть

**Comment by Valtosin** [comment]
до пизды

**Comment by daxsc** [comment]
![image](https://user-images.githubusercontent.com/32306994/144472415-604634b4-c5fc-4eee-8e1b-831d17346e38.png)
