### ISSUE TITLE
[BUG]Аспект и дефибриллятор

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#389]
При аспекте bloody дефибриллятор не воскрешает. Нужно >2 попыток для дефибрилляции человека.
## ID Раунда:

11226
## Как повторить?

Купить аспект bloody и попытаться воскресить человека.

**Comment by Valtosin** [comment]
поебать

**Comment by RedFoxIV** [comment]
у нас болливуд, каждая реанимация сопровождается драматическим ожиданием, пока дохтор по кд пиздит пациента током, прежде чем объявить, что он умер
