### ISSUE TITLE
[BUG] Вампирусы и их баги

### ISSUE THREAD

**Issue by Erring** [frosty-dev/white#390]
Огромное количество найденных багов и фич, найденных у вампиров, которые делают их просто неиграбельными (у них почти всё сломано...). Возможно даже не всё перечислил.
## Как повторить?

1. Immortal heist. 
1) Становимся блудсакером
2) Делаем логово
3) Берём Immortal Heist
4) Активируем её и кликаем на тайтл
5) Бесконечно притягиваемся к этому тайтлу, пока его не удалят или он не поменяется.
2. Masquerade
1) Становимся блудсакером
2) Делаем логово
3) Активируем Masquerade
4) Что без неё, то с, всё равно у вас есть каким-то боком пульс и высвечивается, что у вас всё ок с кожей и с сердцем.
3. После солнечного цикла
1) После того, как вы спрятались в гробу во время дэйлайта, вы теряете зрение...
4. Fortitude
1) С ним всё ок, кроме с...
2) Активировать эту абилку
3) Можно переключать ходьбу и бег, что запрещено поидее самой абилкой.
4) Если убрать роль кровосиси, то она всё ещё будет действовать
5) С ней нельзя уйти в стан от стамины.
5. Кровосисю нельзя уложить в софткрит или хардкрит (может быть это фича)
1) Забиваем кровосисю с 1 левелом до крита
2) Окей... он всё ещё стоит! 
6. Вас прикрепили к  The persuasion rack.
1) Вы отрываетесь от него и... О боже! Вы перевернулись и готовы стать летучей мышкой, эволюционировав в бэтмана! (Нет)
2) Вас не должно просто переворачивать...
7. Возможность выйти до конца дневного цикла.
1) Выходите до конца дневного цикла.

**Comment by Valtosin** [comment]
похуй

**Comment by RedFoxIV** [comment]
кто там вампиров пилил...
