### ISSUE TITLE
[BUG]Я здесь точно сгнию...

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#399]
У ХоСа ( и предположительно у всего СБ) в пермабриге зековский мудлет.

![Screenshot_25](https://user-images.githubusercontent.com/88589686/144713105-4f373514-bef9-4e9f-a8a9-c5ecb2b88106.png)
## ID Раунда:

11313
## Как повторить?

Зайти в пермабриг будучи СБ

**Comment by Valtosin** [comment]
Не баг.
