### ISSUE TITLE
[BUG]Пицца

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#446]
Пицца отображается закрытой, даже когда открыта
![image](https://user-images.githubusercontent.com/88589686/147495965-7abebe7c-f4a1-4793-a028-ac0cac6320f9.png)
![image](https://user-images.githubusercontent.com/88589686/147495974-df08124a-6cb5-4baf-84f9-c5d09ebc0760.png)

## ID Раунда:

11655
## Как повторить?

Нащитспавнить коробку пиццы

**Comment by TequilaSunrise272** [comment]
88bcfea
