### ISSUE TITLE
[BUG]Удаленное управление шлюзом. Отлично

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#476]
Экранчики видно сквозь стены

![image](https://user-images.githubusercontent.com/88589686/148220950-78bd3f03-4140-465b-8d4a-3dddfbb1dc4f.png)
## ID Раунда:
11778
## Как повторить?
Встать на тоже месте

**Comment by TequilaSunrise272** [comment]
![image](https://user-images.githubusercontent.com/27878805/148656222-60a178d6-527b-4ead-b3d9-00769c23f19c.png)
потому что экран на деле расположен здесь, сделано это было так, чтобы с экраном нельзя было взаимодействовать с другой стороны стены
не баг, это бьенд
