### ISSUE TITLE
[IDEA]Власть, которая и не снилась их отцу

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#480]
**Вернуть дворфам возможность создавать имбовые вещи на 100+ форса и практически непробиваемую броню.**
Хочется видеть амплитуду развития кузнечного мастерства, насколько днище было в начале и насколько божественны вещи в конце прокачки.

**Comment by TequilaSunrise272** [comment]
Чтобы потом выдерживать 100 выстрелов с бульдога в упор, даже не получив ни капли урона?

**Comment by Nikitauou** [comment]
Дворфов выпилили 😥
