### ISSUE TITLE
[BUG]Мини-игры, мини-окно

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#535]
Окно у мини-игр слишком мини.
![image](https://user-images.githubusercontent.com/88589686/149636535-d17ba3ae-494f-4a2e-b6f2-8f345515d8fd.png)
## ID Раунда:

11941
## Как повторить?

Открыть окно

**Comment by RedFoxIV** [comment]
оно не растягивается?

**Comment by ThereDrD0** [comment]
Растягивается, но надо же сразу нормально открывать...
