### ISSUE TITLE
[BUG]Coldstation 

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#537]
### Говно с колды:

- **Где плита и духовка???**

![image](https://user-images.githubusercontent.com/88589686/149639970-9d97f71c-af15-4a18-8acc-ef7625653135.png)

- **В роботике нет флешей и сенсоров чувствительности, зато компоненты для медботов положили!!**

![image](https://user-images.githubusercontent.com/88589686/149640027-8fa522dc-bda9-4b6e-9ac1-39a1e2a8425b.png)

- **Капитанский сейф находится прямо в коридоре. Полный доступ по цене 1ой с-4.**

![image](https://user-images.githubusercontent.com/88589686/149640357-86211717-16d8-4e84-82da-276df946d635.png)

- **ГДЕ ПЕРИЛА???**

![image](https://user-images.githubusercontent.com/88589686/149640381-d0432238-4730-4a1a-a629-71d6c40706d0.png)

- **Пермабриг можно покинуть за минуту**

https://youtu.be/Rf1z3aFnQWA

- **Классика блять, питание телекомов обособленно**

![image](https://user-images.githubusercontent.com/88589686/149640446-45220d77-38ce-4a3d-969a-4275bf690c21.png)

- **У всех глав есть кабинеты, а один шкаф РД стоит в углу.**

![image](https://user-images.githubusercontent.com/88589686/149640464-ec632c4b-651c-40c2-a7ac-93fd509a6c34.png)

- **Оружейная, в который нет летального оружия. Дробовики, конечно, можно заправить леталом, но его самого тут нет.**

![image](https://user-images.githubusercontent.com/88589686/149640546-0bbefab3-2f88-44c2-ade0-c60f02904dca.png)

- **Суперполезный медбей в бриге, где нет даже бесплатной аптечки**

![image](https://user-images.githubusercontent.com/88589686/149640589-f19f784f-cc63-40cc-bad0-b28119d3f19b.png)

- **На станции нет мостика, офиса капитана и диска блять**

- **У СЕ нет ни шкафчика, ни офиса**

## ID Раунда:

11942
## Как повторить?

Включить карту

**Comment by ThereDrD0** [comment]
Плюсом у шахтеров нет снаряжения...

**Comment by daxsc** [comment]
фича?
