### ISSUE TITLE
[BUG]Костюм РД

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#597]
Охуенный костюмчик /obj/item/clothing/under/rank/rnd/research_director/vest

![image](https://user-images.githubusercontent.com/88589686/150926174-08412ae3-6b04-4900-8c64-9506ac9456a0.png)
## ID Раунда:

12066
## Как повторить?

Надеть

**Comment by Valtosin** [comment]
@TequilaSunrise272 https://github.com/frosty-dev/white/commit/6df298e829a8077b357878d2c5687d654aecf551

**Comment by ThereDrD0** [comment]
Ты сосал

**Comment by TequilaSunrise272** [comment]
ну все пидор чини сам

**Comment by ThereDrD0** [comment]
Я сломаю путь у лисьего хвоста

**Comment by TequilaSunrise272** [comment]
сделай это

**Comment by RedFoxIV** [comment]
поставь каэсик и играй
