### ISSUE TITLE
[BUG]Бронепластины НЕ КРАФТЯТСЯ

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#599]
Бронепластины нельзя скрафтить, чтобы валера не говорил. https://youtu.be/t4Rd0vbbCYQ
## ID Раунда:

12066
## Как повторить?

Попробуй блять скрафтить

**Comment by Valtosin** [comment]
хуй знает почему конкретно у тебя не крафтится

**Comment by ThereDrD0** [comment]
Крафт заработал лишь после переключения между вкладками

**Comment by Valtosin** [comment]
да и похуй блядь

**Comment by GrishaGold** [comment]
Их теперь в фабрикаторе сб делать можно да и обычным способом тоже...
