### ISSUE TITLE
[BUG]Найтвижн худ

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#601]
ПНВ с худом офицера не имеет этого самого худа офицера
![image](https://user-images.githubusercontent.com/88589686/151040561-d7e027c8-0692-403d-8a09-48901480327d.png)
## ID Раунда:

12073
## Как повторить?

Надеть

**Comment by ThereDrD0** [comment]
Щас ПНВ работает, какая-то частная проблема вообще с интерфейсом СБ у некоторых людей. Его тупо может не быть

**Comment by TequilaSunrise272** [comment]
Ебись со мной блядь хех1! ебись ебись парень. еби бля
