### ISSUE TITLE
[BUG]У инженеров нет доступа к аирконтроллеру

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#628]
Какой гений додумался его убрать? Одна разгерма, ломающая трубы и ебучий инженер нихуя не включит без взлома. А взлом это лишняя ебка
## ID Раунда:

12149
## Как повторить?

Зайти за инженера

**Comment by Valtosin** [comment]
похуй блядь

**Comment by GrishaGold** [comment]
ПОФИКШЕНО...
