### ISSUE TITLE
[IDEA]Навык инженерного дела

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#658]
Добавить навык инженерного дела, отвечающий за:

- Скорость использования инструментов
- Скорость создания структур/вещей в руках
- Скорость крафта
### Польза
Награда инженерам за работу. Полезный эффект микро-наград за каждое действие реально имеется. Пусть такими наградами и станет повышения навыка.

**Comment by Valtosin** [comment]
А плащ нарисуешь?

**Comment by ThereDrD0** [comment]
> А плащ нарисуешь?

Возьми старый плащ СЕ

**Comment by Fesiks** [comment]
уже есть, а не закрыли!
