### ISSUE TITLE
[BUG]Очки рейнжерам

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#816]
Рейнжеры не получают очки за сканирование артефакта, хотя написано, что дает 10 тысяч
## ID Раунда:

13247
## Как повторить?

Отсканировать артефакт и попытаться что-то купить в автомате рейнжеров

**Comment by FelineMistress** [comment]
Этой очки для РНД вроде как, но мне нравится идея, я добавлю такую фишку
