### ISSUE TITLE
[IDEA]Выпилить голосование за карту

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#828]
### I love democracy!!
![image](https://user-images.githubusercontent.com/88589686/164044161-14487f2d-060c-48d7-b920-220b18b852dd.png)
![image](https://user-images.githubusercontent.com/88589686/164044179-5781528d-f564-47c6-ac2f-32472343dafe.png)

Такая система нужна под наш онлайн и к тому же дает игрокам-дебилам сделать выбор в пользу аутизмо-карт, которые убьют онлайн, если такой есть. Да и ночью всех уже тоншит от констракшена или нула
Ну и.. ГДЕ КОРОБКА?!

**Comment by Valtosin** [comment]
формально, это коробка в космосе
