### ISSUE TITLE
[IDEA]Нерф бронепластин

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#837]
### **Бронепластины как осуществление бессмертия**
Сейчас при креплении всех 3ех бронепластин защитные параметры могут доходить до 100% у некоторой брони. Или близко к 100%. Это ломает баланс оружия и делает человека в броне непробиваемым для мили/пуль. 
### **Исправление**

- Для обычных бронежилетов, которые не имеют полной защиты тела, и шлемов максимальное кол-во бронепластин - 2 шт.
- Для РИГов и брони с полным покрытием тела - 1шт.

В том числе это должно работать на комплект защиты рук и ног, добавленный фелином. Он не должен надеваться, если в броне >1 бронепластины

**Comment by FelineMistress** [comment]
Переработано
