### ISSUE TITLE
[BUG]Fuck Encyclopedia

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#838]
Где название????
![image](https://user-images.githubusercontent.com/88589686/164889741-f2706aeb-580f-474e-9acb-34ab56eddf04.png)
![image](https://user-images.githubusercontent.com/88589686/164889746-eb08fc99-19ee-449e-b527-cb67d9905bba.png)

## ID Раунда:

13371
## Как повторить?

Открыть Fish Encyclopedia и посмотреть в чат

**Comment by Valtosin** [comment]
возможно удалим чат
