### ISSUE TITLE
Взлом шкафчиков[IDEA]

### ISSUE THREAD

**Issue by RikCost** [frosty-dev/white#945]
Во время ночного раунда отрубило электричество, повылизали культисты, большинство погибло, но я решил взломать двери и пробраться в кабинет кэпа и украсть карту, чтобы вызвать шатл, но врстретился с проблемой что личный шкафчик не взламывается, как скорее всего и все шкафчики глав отделов. Хотелось бы иметь такую возможность.

**Comment by FelineMistress** [comment]
Для взлома шкафчиков надо делать специальный взломщик в крафт меню или сломать его чем то’ например топором пожарным, но даже в таком случае Карты там нет. Для вызова шаттла надо сломать две консоли вызова шаттла, первая на мостике, вторая у Кэпа
