### ISSUE TITLE
[IDEA]Nerf Xenomorfov

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#954]
Ксеноморфы сейчас - невероятно сильные и имбовые. Считаю, что станбоевка у ксеноморфов, которые сами не станятся - говно.

### **Переработка атак**

- Дизарм сначала выбивает все из рук, потом кладет на землю, потом станит на 1.5 секунды. И для того, чтобы доставить человека в гнездо его нужно будет постоянно закликивать, что будет невозможно, если на помощь пострадавшему прийдет еще кто-то.
- Нейротоксин будет ронять человека, но не станить. Никак тазеров ксеноморфам.
- Грудоломы теперь буду умирать, если носитель умирает.
- Лицехваты должны лечить цель, пока находятся на лице цели. Лечить по 5 всего урона в секунду

### **Новые уязвимости**

- Если ксеноморф из инвиза начинает атаковать в ближнем бою - он перестает быть невидимым.

### **Немного баффов**

- Пока человек пристегнут к гнезду - он не может стрелять. Или можно сделать так, чтобы выстрелы летели очень криво
- Пока человек пристегнут к гнезду - он не может кидаться
- Ксеноморфы могут порвать нахуй одежду цели, когда хармят.
- Харм должен быть острым.

### **Итог**
Ксеноморфы перестанут быть супер-пидорасами, которые станлочат без возможности спаснись и убиваются либо в самом ее зарождении, либо с помощью ЕРТ.

**Comment by Deda565** [comment]
буквально возьми огнемет в руки и кликни, вуаля - ты убил всех ксеносов нахуй

**Comment by ThereDrD0** [comment]
И возможность находиться и работать в смежных комнатах в придачу

**Comment by Alexs410** [comment]
@FelineMistress Закрой, пж.
