### ISSUE TITLE
[BUG]То есть тяните его постоянно

### ISSUE THREAD

**Issue by ThereDrD0** [frosty-dev/white#965]
Пожарная тревога очень криво работает и часто начинает включаться и выключаться периодично. ИИ просто в ахуе от таких тревог

![image](https://user-images.githubusercontent.com/88589686/170706306-6a5f14d2-80d2-42f5-93b1-222becd01636.png)
## ID Раунда:

13866
## Как повторить?

Возможно из-за того, что тревога в соседней комнате, которая потихоньку начинает пробираться в комнату с пожаркой, а атмосферная система чинит эту хуйню. 

![image](https://user-images.githubusercontent.com/88589686/170706522-45057cf2-c13c-4a03-86af-bf481c979067.png)

**Comment by Valtosin** [comment]
проблема решилась сама собой
