### ISSUE TITLE
[BUG] Ёбаный еретик

### ISSUE THREAD

**Issue by GrishaGold** [frosty-dev/white#992]
Если на еретике принести в жертву Хоса (он был без головы) то тебе не засчитается цель и ты не сможешь вознестись. 
Objective #3: Sacrifice 1 head of staff. Fail.
## ID Раунда:
13997
## Как повторить?
Принести в жертву хоса без головы. - Вы не выполнили условие для вознесения.

**Comment by Valtosin** [comment]
не баг
